### ISSUE TITLE
Wrong params in auto-generated code

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/python-libjuju#10]
See ClientFacade.AddMachines() for one example. It accepts arg 'params' of type AddMachineParams, but it should actually accept 'params' of type AddMachines.

Not sure what the proper fix is for this yet. Either the expected type should change, or the auto-generated method body (of AddMachines(), in this example) would need to wrap the passed 'params' in a call to AddMachines.

**Comment by petevg** [comment]
A follow-up on this: I'm still running into trouble, even when I pass in AddMachines as the params.

For example, when I deploy the `hadoop-processing` bundle from the store, I still get the error `juju.errors.JujuAPIError:** json: cannot unmarshal object into Go value of type []params.AddMachineParams` despite applying the fix in the below diff, which I believe is correct (note that I dump the params that I've made .to_json() to make the AddMachines class happy -- it expects to get an array of json objects representing params):

```
diff --git a/juju/model.py b/juju/model.py
index 9d14f82..59dd50b 100644
--- a/juju/model.py
+++ b/juju/model.py
@@ -1255,8 +1255,8 @@ class BundleHandler(object):
         await self.client_facade.AddCharm(None, entity_id)
         return entity_id
 
-    async def addMachines(self, series, constraints, container_type,
-                          parent_id):
+    async def addMachines(self, series=None, constraints=None, container_typNo
ne,                                                                           
+                          parent_id=None):
         """
         :param series string:
             Series holds the optional machine OS series.
@@ -1281,7 +1281,8 @@ class BundleHandler(object):
             container_type=container_type,
             parent_id=self.resolve(parent_id),
         )
-        results = await self.client_facade.AddMachines(params)
+        results = await self.client_facade.AddMachines(
+            client.AddMachines([params.to_json()]))
         log.debug('Added new machine %s', results[0].machine)
         return results[0].machine
```

**Comment by tvansteenburgh** [comment]
Have you tried it without the `.to_json()`? i.e.:

    results = await self.client_facade.AddMachines(client.AddMachines([params]))

To be clear, there is still a bug here (in the facade generation). But afaict your workaround should work in the meantime. But it looks me like you don't need the `.to_json()` in your example.

**Comment by petevg** [comment]
@tvansteenburgh Without the to_json, it raises an exception in the AddMachines class, as that class attempts to unpack params from json.

**Comment by petevg** [comment]
@tvansteenburgh Trace, for posterity:

```
Traceback (most recent call last):
  File "/home/petevg/Desktop/poke_at_model.py", line 14, in main
    await _main(model, log)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/petevg/Desktop/poke_at_model.py", line 84, in _main
    await i(model, log)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/petevg/Desktop/poke_at_model.py", line 80, in deploy
    await model.deploy('hadoop-processing')
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/petevg/Code/python-libjuju/juju/model.py", line 832, in deploy
    await handler.execute_plan()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/petevg/Code/python-libjuju/juju/model.py", line 1232, in execute_plan
    result = await method(*step.args)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/petevg/Code/python-libjuju/juju/model.py", line 1285, in addMachines
    client.AddMachines([params]))
  File "/home/petevg/Code/python-libjuju/juju/client/_client.py", line 1514, in __init__
    self.params = [AddMachineParams.from_json(o) for o in params or []]
  File "/home/petevg/Code/python-libjuju/juju/client/_client.py", line 1514, in <listcomp>
    self.params = [AddMachineParams.from_json(o) for o in params or []]
  File "/home/petevg/Code/python-libjuju/juju/client/facade.py", line 444, in from_json
    for k, v in (data or {}).items():
AttributeError: 'AddMachineParams' object has no attribute 'items'
```

**Comment by petevg** [comment]
Getting rid of the json parsing entirely just gets me back to the original error unmarshalling the object. :-/

Refactor, for reference:

```
diff --git a/juju/client/_client.py b/juju/client/_client.py
index 69fbc4c..6e6df96 100644
--- a/juju/client/_client.py
+++ b/juju/client/_client.py
@@ -1511,7 +1511,7 @@ class AddMachines(Type):
         '''
         params : typing.Sequence<+T_co>[~AddMachineParams]<~AddMachineParams>
         '''
-        self.params = [AddMachineParams.from_json(o) for o in params or []]
+        self.params = params or []
 
 
 class AddMachinesResult(Type):
diff --git a/juju/model.py b/juju/model.py
index 59dd50b..540f7b7 100644
--- a/juju/model.py
+++ b/juju/model.py
@@ -1282,7 +1282,7 @@ class BundleHandler(object):
             parent_id=self.resolve(parent_id),
         )
         results = await self.client_facade.AddMachines(
-            client.AddMachines([params.to_json()]))
+            client.AddMachines([params]))
         log.debug('Added new machine %s', results[0].machine)
         return results[0].machine
```

**Comment by petevg** [comment]
@tvansteenburgh @johnsca Progress! The below pasted diff seems to get us through AddMachines successfully. We then get hung up on passing an instance.Placement object in later on in the process, but perhaps that is a separate bug.

The diff fixes the following issues:

1) model.py was expecting arguments, but was getting passed a dict.
2) Per @johnsca's research, the way that we handle constraints is broken; we need to parse them; since we don't, we get a json error.
3) If we want to pass in an AddMachines class, the thing that `def AddMachines` does, with packing things into a dict needs to not happen.

```
diff --git a/juju/client/_client.py b/juju/client/_client.py
index 69fbc4c..f4bd70a 100644
--- a/juju/client/_client.py
+++ b/juju/client/_client.py
@@ -1511,7 +1511,7 @@ class AddMachines(Type):
         '''
         params : typing.Sequence<+T_co>[~AddMachineParams]<~AddMachineParams>
         '''
-        self.params = [AddMachineParams.from_json(o) for o in params or []]
+        self.params = params or []
 
 
 class AddMachinesResult(Type):
@@ -9399,9 +9399,7 @@ class ClientFacade(Type):
         Returns -> typing.Sequence<+T_co>[~AddMachinesResult]<~AddMachinesResult>
         '''
         # map input types to rpc msg
-        _params = dict()
-        msg = dict(type='Client', request='AddMachines', version=1, params=_params)
-        _params['params'] = params
+        msg = dict(type='Client', request='AddMachines', version=1, params=params)
         reply = await self.rpc(msg)
         return reply
 
diff --git a/juju/model.py b/juju/model.py
index 9d14f82..ed4ce6f 100644
--- a/juju/model.py
+++ b/juju/model.py
@@ -1255,8 +1255,7 @@ class BundleHandler(object):
         await self.client_facade.AddCharm(None, entity_id)
         return entity_id
 
-    async def addMachines(self, series, constraints, container_type,
-                          parent_id):
+    async def addMachines(self, params):
         """
         :param series string:
             Series holds the optional machine OS series.
@@ -1275,15 +1274,15 @@ class BundleHandler(object):
             case this machine is a container, in which case also ContainerType
             is set.
         """
-        params = client.AddMachineParams(
-            series=series,
-            constraints=constraints,
-            container_type=container_type,
-            parent_id=self.resolve(parent_id),
-        )
-        results = await self.client_facade.AddMachines(params)
-        log.debug('Added new machine %s', results[0].machine)
-        return results[0].machine
+        del params["constraints"]  # Temp clobbering constraints, as our parsing is broken
+        if 'parent_id' in params:
+            params['parent_id'] = self.resolve(params['parent_id'])
+
+        params = client.AddMachineParams(**params)
+        results = await self.client_facade.AddMachines(
+            client.AddMachines([params]))
+        log.debug('Added new machine %s', results.machines[0].machine)
+        return results.machines[0].machine
 
     async def addRelation(self, endpoint1, endpoint2):
         """
```

**Comment by petevg** [comment]
@johnsca prodded me to try dropping the bit where we stuff things into an AddMachines class. It simplifies the diff (though we still need to fix constraints parsing):

```
diff --git a/juju/model.py b/juju/model.py
index 9d14f82..8f03eca 100644
--- a/juju/model.py
+++ b/juju/model.py
@@ -1255,8 +1255,7 @@ class BundleHandler(object):
         await self.client_facade.AddCharm(None, entity_id)
         return entity_id
 
-    async def addMachines(self, series, constraints, container_type,
-                          parent_id):
+    async def addMachines(self, params):
         """
         :param series string:
             Series holds the optional machine OS series.
@@ -1275,15 +1274,14 @@ class BundleHandler(object):
             case this machine is a container, in which case also ContainerType
             is set.
         """
-        params = client.AddMachineParams(
-            series=series,
-            constraints=constraints,
-            container_type=container_type,
-            parent_id=self.resolve(parent_id),
-        )
-        results = await self.client_facade.AddMachines(params)
-        log.debug('Added new machine %s', results[0].machine)
-        return results[0].machine
+        del params["constraints"]  # Temp clobbering constraints, as our parsing is broken
+        if 'parent_id' in params:
+            params['parent_id'] = self.resolve(params['parent_id'])
+
+        params = client.AddMachineParams(**params)
+        results = await self.client_facade.AddMachines([params])
+        log.debug('Added new machine %s', results.machines[0].machine)
+        return results.machines[0].machine
 
     async def addRelation(self, endpoint1, endpoint2):
         """
```

**Comment by petevg** [comment]
Update on this: it looks like we also need to specific a default of ['JobHostUnits'] for the jobs param, check for errors, and do some parsing of the constraints. Reading through the Go code, it looks like it does things like expand "8G" into an int (8 * 1024^3). I'm having a hard time figuring out exactly where all the Go aliases live, so that we can write some reliable Python against it.

Maybe there's a way to pass in the raw string, and convince the api to do the parsing?

We also still run into that Placement class error even after I get the AddMachines stuff working, with temp code in place to parse the constraints that the hadoop-processing bundle specifies.

**Comment by petevg** [comment]
Addressed by https://github.com/juju/python-libjuju/pull/21 (it's not a problem in the generated code, after all)
