### ISSUE TITLE
Failed to add machine from MAAS using machine's FQDN (known in MAAS)

### ISSUE THREAD

**Issue by gboutry** [juju/python-libjuju#1019]
### Description

I'm failing to use `model.add_machine` to add a machine known to MAAS to a model hosted on controller connected to a MAAS cloud. (controller has been bootstrapped to the MAAS cloud even)

Error:
```
machine = await model.add_machine(spec="sb-n1.maas", series="jammy")
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/snap/openstack/x69/lib/python3.10/site-packages/juju/model.py", line 1458, in add_machine
    raise ValueError("Error adding machine: %s" % error.message)
ValueError: Error adding machine: invalid model name "sb-n1.maas"
```

### Urgency

Casually reporting

### Python-libjuju version

3.2.0.0

### Juju version

3.2.4

### Reproduce / Test

```python
from juju.controller import Controller

controller = Controller()
await controller.connect(
                endpoint=<endpoints>,
                cacert=<ca>,
                username=<user>,
                password=<password>,
            )
model = await controller.get_model("openstack-machines")
machine = await model.add_machine(spec="sb-n1.maas", series="jammy")
print("Machine created: {}".format(machine.entity_id))
```

**Comment by gboutry** [comment]
Looks like there's some sort of relation with this bug: https://bugs.launchpad.net/juju/+bug/2056501
