### ISSUE TITLE
Receiving a KeyError while trying to access an model attribute with getattr is unexpected 

### ISSUE THREAD

**Issue by gabrielcocenza** [juju/python-libjuju#1048]
### Description

I'm using pythonlib juju version `2.9.44.0` and when an Action fails, we are trying to create a custom exception for the user.

This is the snippet of the code:

```python
class ActionFailed(COUException):
    """Exception raised when action fails."""

    # pylint: disable=consider-using-f-string
    def __init__(self, action: Action, output: Optional[Union[Any, dict]] = None):
        """Set information about action failure in message and raise.

        :param action: Action that failed.
        :type action: Action
        :param output: Description of the failed action, defaults to None
        :type output: Optional[str], optional
        """
        params = {"output": output}
        for key in [
            "name",
            "parameters",
            "receiver",
            "message",
            "id",
            "status",
            "enqueued",
            "started",
            "completed",
        ]:
            params[key] = getattr(action, key, "<not-set>")

        message = (
            'Run of action "{name}" with parameters "{parameters}" on '
            '"{receiver}" failed with "{message}" (id={id} '
            "status={status} enqueued={enqueued} started={started} "
            "completed={completed} output={output})".format(**params)
        )
        super().__init__(message)
```

Running this will give the following traceback:
```
2024-05-01 13:43:18 [cou.utils.juju_utils] [INFO] function _get_waited_action_object failed [0]
Traceback (most recent call last):
  File "/home/ubuntu/cocenza/charmed-openstack-upgrader-1/cou/utils/juju_utils.py", line 116, in wrapper
    return await func(*args, **kwargs)
  File "/home/ubuntu/cocenza/charmed-openstack-upgrader-1/cou/utils/juju_utils.py", line 257, in _get_waited_action_object
    raise ActionFailed(action, output=action_obj.data)
  File "/home/ubuntu/cocenza/charmed-openstack-upgrader-1/cou/exceptions.py", line 102, in __init__
    params[key] = getattr(action, key, "<not-set>")
  File "/home/ubuntu/cocenza/charmed-openstack-upgrader-1/.venv/lib/python3.10/site-packages/juju/model.py", line 284, in __getattr__
    return self.safe_data[name]
KeyError: 'parameters'
```

I think the libjuju should return `AttributeError` instead of raising `Keyerror` on https://github.com/juju/python-libjuju/blob/c7ccc231615f244cde44ba254b795d79f3a60735/juju/model.py#L281-L293

Raising AttributeError when not found will let users of the API decide what to do.

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.44.0

### Juju version

2.9.49

### Reproduce / Test

```python
The example above is easily reproducible
```

**Comment by Aflynn50** [comment]
I believe `KeyError` is more appropriate here. According to the [AttributeError python docs](https://docs.python.org/3/library/exceptions.html#AttributeError), it should be raised when you try and get a none existant attirbute of an object, e.g. 
```
X = 10
# Raises an AttributeError
X.append(6)
```
`KeyError` is raised [when a value is not in a dictionary](https://docs.python.org/3/library/exceptions.html#KeyError). `getattr` is looking up the key `"parameters"` in its `safe_data` dictionary, so it is natural that you would get a `KeyError`.
