### ISSUE TITLE
Failed to add_model to microk8s

### ISSUE THREAD

**Issue by SimonRichardson** [juju/python-libjuju#1080]
### Description

Using python 3.5.2 fails to add-model to microk8s.

### Urgency

Casually reporting

### Python-libjuju version

3.5.2

### Juju version

3.5.2

### Reproduce / Test

```python
import logging

from juju import jasyncio
from juju.controller import Controller

async def main():
    controller = Controller()
    await controller.connect()
    await controller.add_model('chat')
}

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    ws_logger = logging.getLogger('websockets.protocol')
    ws_logger.setLevel(logging.INFO)
    jasyncio.run(main())
```

```
DEBUG:websockets.client:> TEXT '{\n  "type": "ModelManager",\n  "request": "Cre...,\n  "request-id": 6\n}' [1030 bytes]
DEBUG:websockets.client:< TEXT '{"request-id":6,"error":"failed to open kuberne...valid","response":{}}\n' [394 bytes]
DEBUG:juju.client.connection:connection id : 140279176385808 <--- {'request-id': 6, 'error': 'failed to open kubernetes client: annotations map[controller.juju.is/id:d7c98020-8878-4513-8ebd-4d00b27be030 model.juju.is/id:c2812154-6c77-411f-88ae-beb6539e6d64] for namespace "chat" not valid must include map[controller.juju.is/id:d7c98020-8878-4513-8ebd-4d00b27be030 model.juju.is/id:a58e7db4-8429-4828-83eb-722973958d11]', 'error-code': 'not valid', 'response': {}}
Traceback (most recent call last):
  File "/home/ubuntu/pylibjuju/pylibjuju.py", line 46, in <module>
    jasyncio.run(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/jasyncio.py", line 110, in run
    raise task.exception()
  File "/home/ubuntu/pylibjuju/pylibjuju.py", line 17, in main
    my_model = await controller.add_model('chat')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/controller.py", line 358, in add_model
    model_info = await model_facade.CreateModel(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/client/facade.py", line 486, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/client/_client9.py", line 624, in CreateModel
    reply = await self.rpc(msg)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/client/facade.py", line 659, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/client/connection.py", line 672, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: failed to open kubernetes client: annotations map[controller.juju.is/id:d7c98020-8878-4513-8ebd-4d00b27be030 model.juju.is/id:c2812154-6c77-411f-88ae-beb6539e6d64] for namespace "chat" not valid must include map[controller.juju.is/id:d7c98020-8878-4513-8ebd-4d00b27be030 model.juju.is/id:a58e7db4-8429-4828-83eb-722973958d11]
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<WebSocketCommonProtocol.keepalive_ping() running at /home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py:1254> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task_Pinger' coro=<Connection._pinger() running at /home/ubuntu/.local/lib/python3.10/site-packages/juju/client/connection.py:615> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task_Receiver' coro=<Connection._receiver() running at /home/ubuntu/.local/lib/python3.10/site-packages/juju/client/connection.py:565> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f954a65f7f0>
transport: <_SelectorSocketTransport closing fd=9>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at /home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py:1301> wait_for=<Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>>
DEBUG:websockets.client:x closing TCP connection
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f954a646ff0>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1337, in close_connection
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1355, in close_transport
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1379, in wait_for_connection_lost
  File "/home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/async_timeout.py", line 74, in timeout
RuntimeError: no running event loop
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-23' coro=<WebSocketCommonProtocol.recv() running at /home/ubuntu/.local/lib/python3.10/site-packages/websockets/legacy/protocol.py:552> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=<Logger juju....ction (DEBUG)>)() at /home/ubuntu/.local/lib/python3.10/site-packages/juju/jasyncio.py:39]>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-24' coro=<Event.wait() running at /usr/lib/python3.10/asyncio/locks.py:214> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```
```

**Comment by tmihoc** [comment]
@PietroPasotti has encountered something similar when using pytest-operator.

**Comment by PietroPasotti** [comment]
yeh I can't locally run integration tests for a while now

**Comment by ycliuhw** [comment]
I wasn't able to reproduce it on my local.
```
juju version
3.5.3-ubuntu-amd64

snap info microk8s | grep installed
installed:               v1.28.10            (6829) 186MB -
```

Is it reproducible in a newly installed microk8s cluster?

My test result:

```python
import logging

from juju import jasyncio
from juju.controller import Controller
```


```python
logging.basicConfig(level=logging.DEBUG)
ws_logger = logging.getLogger('websockets.protocol')
ws_logger.setLevel(logging.INFO)
```


```python
controller = Controller()
```


```python
await controller.connect()
```

```python
await controller.add_model('chat')
```


```python
await controller.list_models()
```

    ['chat', 'controller']

**Comment by tmihoc** [comment]
Looks like the cluster might have been in an error state. Retried from scratch and now it worked.
