### ISSUE TITLE
KeyError: server-version

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#111]
When connecting to JAAS:

```
2017-04-20 10:19:49,027 [INFO] conjure-up/kubernetes-core - juju.py:128 - Connecting to model jaas:conjure-kubernetes-core-a5e...
2017-04-20 10:19:49,583 [INFO] conjure-up/kubernetes-core - websocket: connection.py:161 - Driver connected to juju wss://jimm.jujucharms.com:443/model/5f2eb0cd-2c30-4033-8424-587d6db851ba/api
2017-04-20 10:19:50,836 [INFO] conjure-up/kubernetes-core - websocket: connection.py:161 - Driver connected to juju wss://1.eu-west-1.aws.jaas.jujucharms.com:443/model/5f2eb0cd-2c30-4033-8424-587d6db851ba/api
2017-04-20 10:19:51,679 [INFO] conjure-up/kubernetes-core - websocket: connection.py:161 - Driver connected to juju wss://1.eu-west-1.aws.jaas.jujucharms.com:443/model/5f2eb0cd-2c30-4033-8424-587d6db851ba/api
2017-04-20 10:19:52,089 [ERROR] conjure-up/kubernetes-core - juju.model: model.py:648 - Error in watcher
Traceback (most recent call last):
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 440, in build_facades
    self.facades = VERSION_MAP[self.info['server-version']]
KeyError: 'server-version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/model.py", line 624, in _start_watch
    self._watch_conn = await self.connection.clone()
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 295, in clone
    self.loop,
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 328, in connect
    await client.login(username, password, macaroons)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 467, in login
    self.build_facades(response.get('facades', {}))
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 444, in build_facades
    self.info['server-version']))
KeyError: 'server-version'
```

**Comment by johnsca** [comment]
I'm not able to replicate this, so it seems to have been a transient error, but it's probably worth catching.  Low priority, though, unless it comes up again.

**Comment by johnsca** [comment]
I accidentally duplicated this bug with more details in #114.  Closing this in favor of that one.
