### ISSUE TITLE
'KubernetesProxy' object has no attribute 'temp_ca_file' in tests

### ISSUE THREAD

**Issue by dimaqq** [juju/python-libjuju#1154]
### Description

tests pass, but following error is reported:

### Urgency

Casually reporting

### Python-libjuju version

3.5.2.0

### Juju version

any

### Reproduce / Test

```python
# tox -e unit

tests/unit/test_proxy_kubernetes.py::TestKubernetesProxy::test_remote_port_error
  /code/python-libjuju/.tox/py3/lib/python3.12/site-packages/_pytest/unraisableexception.py:85: PytestUnraisableExceptionWarning: Exception ignored in: <function KubernetesProxy.__del__ at 0xee3a9ca1c040>

  Traceback (most recent call last):
    File "/code/python-libjuju/juju/client/proxy/kubernetes/proxy.py", line 34, in __init__
      self.remote_port = int(remote_port)
                         ^^^^^^^^^^^^^^^^
  ValueError: invalid literal for int() with base 10: 'not-a-integer-port'

  During handling of the above exception, another exception occurred:

  ValueError: Invalid port number: not-a-integer-port

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/code/python-libjuju/juju/client/proxy/kubernetes/proxy.py", line 67, in __del__
      os.unlink(self.temp_ca_file.name)
                ^^^^^^^^^^^^^^^^^
  AttributeError: 'KubernetesProxy' object has no attribute 'temp_ca_file'

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

**Comment by dimaqq** [comment]
I believe it's a simple bug, the attribute is set conditionally on construction and removed unconditionally or something like that.

**Comment by dimaqq** [comment]
Done in #1186
