### ISSUE TITLE
juju.errors.JujuAPIError: unknown version (4) of interface "Application"

### ISSUE THREAD

**Issue by mreed8855** [juju/python-libjuju#135]
Hi 

I am consistently running into this error with a fresh install of libjuju, were previously I didn't see it.  appears to be related to issue #49 and issue #85.  Is anyone else seeing this and if so how did you get around it?

```
DEBUG:asyncio:Using selector: EpollSelector
INFO:root:Connecting to controller
INFO:websocket:Driver connected to juju wss://192.168.122.78:17070/api
WARNING:websocket:Could not find a set of facades for 2.1.3. Using the latest facade set instead
DEBUG:juju.controller:Creating model scalebotjenkins-postgres-test-3
DEBUG:juju.controller:Exec ('juju', 'add-ssh-key', '-m', 'scalebotjenkins-postgres-test-3', 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT8aLjRLBvNZG72sb0pHu8mQd+ymRy7LixE8bT7j851Bosz1nVLibgQPY8LGssBkUsi4JnDnCT3/XTtF3Ws7cr2CZyYiHYK+2s0duTOVY7lt1OPaWE3k1Tt0waVJC26SGi6b1fycVQzGbLa0AwvfbqUnp34zeA4p5sQSuuJWnwwCw1p55MNqxRbMmyu70GTQ+ijnjOqpAoaraNrKNO2qQ0yeGs2c9jp+4ZjwmfbetaVJp7C+Tn0pkxJCXo64i3p4ar7TdzYJdNZ3soa9E7aavzBNi729rSCcd5Y90B2M/qZTj5w/swidqfS8pKZlnptLbwzS3O1MNossUN8jv0L0on juju-client-key') -> 0
INFO:websocket:Driver connected to juju wss://192.168.122.78:17070/model/7dc78519-de9a-4bfc-82a6-0259c264452d/api
WARNING:websocket:Could not find a set of facades for 2.1.3. Using the latest facade set instead
DEBUG:juju.model:Starting watcher task
INFO:websocket:Driver connected to juju wss://192.168.122.78:17070/model/7dc78519-de9a-4bfc-82a6-0259c264452d/api
WARNING:websocket:Could not find a set of facades for 2.1.3. Using the latest facade set instead
DEBUG:juju.model:Got ModelInfo: {'migration': None, 'default_series': 'xenial', 'uuid': '7dc78519-de9a-4bfc-82a6-0259c264452d', 'cloud_tag': 'cloud-localmaas', 'controller_uuid': '', 'provider_type': 'maas', 'users': [], 'name': 'scalebotjenkins-postgres-test-3', 'cloud_credential_tag': 'cloudcred-localmaas_admin_mreed', 'owner_tag': 'user-admin', 'life': 'alive', 'sla': None, 'cloud_region': None, 'status': <juju.client._definitions.EntityStatus object at 0x7f9dac49a7b8>, 'machines': []}
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/postgresql/meta/any?include=bundle-machine-count&include=bundle-metadata&include=bundle-unit-count&include=bundles-containing&include=charm-config&include=charm-metadata&include=common-info&include=extra-info&include=owner&include=revision-info&include=published&include=stats&include=resources&include=supported-series&include=terms HTTP/1.1" 200 6894

INFO:juju.model:Deploying cs:postgresql-148
ERROR:root:Test failed! Model scalebotjenkins-postgres-test-3 may not be cleaned up
Traceback (most recent call last):
  File "/srv/scalebot/repo/tests/postgres/run_postgres.py", line 52, in main
    'tags': [argstags],
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1077, in deploy
    placement=parse_placement(to)
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1140, in _deploy
    result = await app_facade.Deploy([app])
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 393, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/_client4.py", line 486, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 515, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 217, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: unknown version (4) of interface "Application"
INFO:root:unknown version (4) of interface "Application"
DEBUG:juju.model:Stopping watcher task
DEBUG:juju.model:Closing watcher connection
DEBUG:juju.model:Closing model connection
DEBUG:juju.controller:Closing controller connection
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Connection.pinger() running at /usr/local/lib/python3.5/dist-packages/juju/client/connection.py:199> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Connection.pinger() running at /usr/local/lib/python3.5/dist-packages/juju/client/connection.py:199> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Connection.pinger() running at /usr/local/lib/python3.5/dist-packages/juju/client/connection.py:199> wait_for=<Future pending cb=[Task._wakeup()]>>
Destroying model

Waiting on model to be removed...

Waiting on model to be removed...

Waiting on model to be removed...

Waiting on model to be removed...

Waiting on model to be removed...

Waiting on model to be removed...
```

**Comment by johnsca** [comment]
Can you please confirm your version of libjuju, because the warning `Could not find a set of facades for 2.1.3. Using the latest facade set instead` was [removed](https://github.com/juju/python-libjuju/commit/6a363710a84d62a6ad1268045f319611f356f453) in [0.4.1](https://pythonhosted.org/juju/#id4).

**Comment by mreed8855** [comment]
Looks like I have an older version,  I have 0.4.0.  I will upgrade and see if that fixes it.  Thanks!  :-)

pip3 show juju
---
Metadata-Version: 2.0
Name: juju
Version: 0.4.0
Summary: Python library for Juju

**Comment by mreed8855** [comment]
This seems to have fixed my issue, as I have updated to 0.5.0.  I am still seeing the following message while the system is deploying, however this could be an issue with my setup.  I am going to mark this as closed for the time being.  Thanks for the help johnsca  :-)

DEBUG:juju.machine:Overriding machine delta with FullStatus data
DEBUG:juju.machine:    agent-version:  -> 2.1.3
DEBUG:juju.machine:    current: pending -> running
DEBUG:juju.machine:    message:  -> Deployed
DEBUG:juju.machine:    since: 2017-06-09T21:11:51.167300277Z -> 2017-06-09T21:17:22.089799791Z

**Comment by johnsca** [comment]
Those messages are expected debug output from #133 which contains a work-around for https://bugs.launchpad.net/juju/+bug/1695335

Are they causing you an issue somehow?

**Comment by mreed8855** [comment]
No issues,  and I didn't realize it was expected, my mistake.  :-)
