### ISSUE TITLE
asyncio task destroying handling

### ISSUE THREAD

**Issue by dphuang2** [juju/python-libjuju#151]
Hi, I have been developing with this library for a bit now and only recently ran into this issue.

I am currently running into is an issue with loop.run executions throwing errors on python execution exit. Here is an example of a simple snippet that throws an error:

**Code:**
```
from juju import loop
from juju.model import Model

mod = Model()
loop.run(mod.connect_current())
```
**Error at end of file:**
```
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.run() running at /home/ubuntu/.local/lib/python3.5/site-packages/websockets/protocol.py:414> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/
python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Connection.pinger() running at /home/ubuntu/.local/lib/python3.5/site-packages/juju/client/connection.py:232> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Connection.pinger.<locals>._do_ping() done, defined at /home/ubuntu/.local/lib/python3.5/site-packages/juju/client/connection.py:219> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completi
on() at /usr/lib/python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<AllWatcherFacade.Next() running at /home/ubuntu/.local/lib/python3.5/site-packages/juju/client/facade.py:392> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3
.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Event.wait() running at /usr/lib/python3.5/asyncio/locks.py:264> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Queue.get() running at /usr/lib/python3.5/asyncio/queues.py:168> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib/python3.5/asyncio/tasks.py:415]>
Exception ignored in: <coroutine object AllWatcherFacade.Next at 0x7fdd1940b308>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/client/facade.py", line 392, in wrapper
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/client/_client1.py", line 59, in Next
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/client/overrides.py", line 104, in rpc
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/client/connection.py", line 260, in rpc
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/client/connection.py", line 179, in recv
  File "/home/ubuntu/.local/lib/python3.5/site-packages/juju/utils.py", line 60, in get
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <generator object Queue.get at 0x7fdd19729f10>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 483, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 492, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 320, in _check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.recv() running at /home/ubuntu/.local/lib/python3.5/site-packages/websockets/protocol.py:285> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib
/python3.5/asyncio/tasks.py:415]>
Task was destroyed but it is pending!
task: <Task pending coro=<Model._watch.<locals>._all_watcher() running at /home/ubuntu/.local/lib/python3.5/site-packages/juju/model.py:658> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Connection.receiver() running at /home/ubuntu/.local/lib/python3.5/site-packages/juju/client/connection.py:187> wait_for=<Future pending cb=[Task._wakeup()]>>
```

To clarify, this is not a runtime error. The error occurs as the Python execution exits.

I tried reverting to 0.5.2 thinking that the recent changes were the cause of this but it threw the same error.

Any ideas as to why this is happening and how to fix it?

**Comment by johnsca** [comment]
This is happening because you're not disconnecting the model cleanly, so the background tasks used to keep the model up to date, handle websocket communication, etc, are forcibly ended.  If you add `model.disconnect()` to the run list, it should clear up the errors:

```python
from juju import loop
from juju.model import Model

mod = Model()
loop.run(
    mod.connect_current(),
    mod.disconnect(),
)
```

**Comment by dphuang2** [comment]
oh, my bad!
