### ISSUE TITLE
JujuAPIError: unknown watcher id

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#156]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/model.py", line 659, in _all_watcher
    self.loop)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/utils.py", line 94, in run_with_interrupt
    result = [f.result() for f in done if f is not event_task]
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/utils.py", line 94, in <listcomp>
    result = [f.result() for f in done if f is not event_task]
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/facade.py", line 392, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/_client1.py", line 59, in Next
    reply = await self.rpc(msg)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/overrides.py", line 105, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/johnsca/juju/conjure-up/conjure-dev/lib/python3.5/site-packages/juju/client/connection.py", line 267, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: unknown watcher id
```

**Comment by petevg** [comment]
This looks like a bug on the core api side (unless we're managing to munge the AllWatcher id in some request -- maybe we're clobbering a json param somehow?).

If you take a look in https://github.com/juju/juju/blob/develop/apiserver/watcher.go, you'll see that common.ErrUnknownWatcher gets raised when it tries to look up a watcher by id, and can't. I don't believe that we ever touch that id, though -- we just get it back from an API call. It feels like something funky happened API side.

**Comment by johnsca** [comment]
I wonder if the watcher is somehow being invalidated from the controller's side and we should handle this gracefully by reconnecting the watcher like we now do when it detects a dropped connection.

**Comment by petevg** [comment]
That makes a lot of sense.

I also wonder what would happen in the opposite situation, when we get disconnected due to an error on our end. Can we reconnect via WatcherID, and pick up where we left off?

That's a thing for a different github issue, though. Hooking in to the existing code that restarts a watcher when we run into this error should work well.
