### ISSUE TITLE
Error connecting to current model

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#190]
Trying to run `examples/relate.py` and I get this:

```
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "examples/relate.py", line 98, in <module>
    loop.run(main())
  File "/home/johnsca/juju/python-libjuju/juju/loop.py", line 38, in run
    raise task.exception()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "examples/relate.py", line 43, in main
    await model.connect()
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 445, in connect
    await self._connector.connect_model(model_name)
  File "/home/johnsca/juju/python-libjuju/juju/client/connector.py", line 115, in connect_model
    uuid=models['models'][model_name]['uuid'],
KeyError: 'lxd:admin/rel1'
```

The model exists and is in the Juju data files, but it seems like the controller name portion is causing an issue.  @rogpeppe I think this is related to your connection refactors?

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
