### ISSUE TITLE
Compatibility breaks

### ISSUE THREAD

**Issue by AdamIsrael** [juju/python-libjuju#212]
I've been working on a codebase written against 0.6.1. I'm updating to use the latest (0.7.3) and have run into a few compatibility breaks that I'm documenting here. I'll add to this list as I complete my upgrade.

- Connection.connect no longer accepts positional arguments

The previous usage was:
```
Controller.connect(endpoint, user, secret, cacert)
```
The current method signature requires this:
```
Controller.connect(endpoint=endpoint, username=user, password=secret, cacert=cacert)
```

- Connection.get_models() throws an exception
Note: `get_models()` has been deprecated in favour of `list-models()`, which is more appropriate in my use-case, but should not be throwing this error.
```
Traceback (most recent call last):                                                                                                      
  File "/home/stone/src/osm/N2VC/tests/test_python.py", line 264, in test_deploy_application                                            
    self.loop.run_until_complete(n.DeployVNF(nsd, vnfd))            
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete                                                     
    return future.result()                                                                                                              
  File "/home/stone/src/osm/N2VC/n2vc/vnf.py", line 207, in DeployVNF                                                                   
    models = await self.controller.get_models()                     
  File "/home/stone/.local/lib/python3.6/site-packages/juju/controller.py", line 318, in get_models                                     
    self.connection)                                                                                                                    
  File "/home/stone/.local/lib/python3.6/site-packages/juju/client/_client.py", line 48, in from_connection                             
    version = connection.facades.get(facade_name)                   
AttributeError: 'function' object has no attribute 'facades'        
```

**Comment by johnsca** [comment]
`Controller.connect_current` was removed.
