### ISSUE TITLE
Self-hosted controllers require auth-tag even with macaroon auth

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#216]
Originally reported by @mitechie via IRC

It seems that connecting to self-hosted controllers with macaroon auth fails with the following error:

```
Traceback (most recent call last):
  File "examples/connect_current_model.py", line 26, in <module>
    loop.run(main())
  File "/home/johnsca/juju/python-libjuju/juju/loop.py", line 38, in run
    raise task.exception()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "examples/connect_current_model.py", line 16, in main
    await model.connect()
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 507, in connect
    await self._connector.connect_model(model_name, **kwargs)
  File "/home/johnsca/juju/python-libjuju/juju/client/connector.py", line 140, in connect_model
    bakery_client=self.bakery_client_for_controller(controller_name),
  File "/home/johnsca/juju/python-libjuju/juju/client/connector.py", line 68, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 168, in connect
    await self._connect_with_redirect([(endpoint, cacert)])
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 511, in _connect_with_redirect
    login_result = await self._connect_with_login(endpoints)
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 483, in _connect_with_login
    result = (await self.login())['response']
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 538, in login
    "params": params,
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 316, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: no credentials provided
```

We confirmed that the macaroon is indeed being sent, and after some additional testing I discovered that the `auth-tag` is required, even though that info is encoded into the macaroon.  As it doesn't hurt anything to send it anyway, we should just unconditionally supply it.

**Comment by johnsca** [comment]
Easiest way to replicate this is to bootstrap a LXD controller, do `juju change-user-password`, and then try running `examples/connect_current_model.py`.  I'd like to add an automated test for this, but it would potentially break all of the other tests, so I'm not sure it's a good idea.
