### ISSUE TITLE
unit.scp_to results in "TypeError: signal handler..." exception

### ISSUE THREAD

**Issue by gnuoy** [juju/python-libjuju#219]
Python 3.5.2
libjuju 0.7.3

Running unit.scp_to successfully scp's a file to the unit in question but throws the following stacktrace:
 
```
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

I think this is because loop needs an explicit close in later versions of Python. I am some what out of my depth here so I may well be wrong :-)

I can reproduce the error with:

```
#!/usr/bin/env python3

from juju import loop
from juju.model import Model

async def scp_to_unit():
    model = Model()
    await model.connect_current()
    try:
        unit = model.applications['vault'].units[0]
        await unit.scp_to('/tmp/tmb.txt', '/tmp/tmb.txt')
    finally:
        # Disconnect from the api server and cleanup.
        await model.disconnect()

loop.run(scp_to_unit())
```

**Comment by gnuoy** [comment]
Closing the loop explicitly was all that was needed. asyncio.get_event_loop().close()
