### ISSUE TITLE
SSL cert error during macaroon discharge on localhost

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#229]
I'm not sure how the macaroon discharge process is supposed to work with a localhost provider (the juju CLI client prompts for the password, so it's probably not going to work without a password regardless), but this error seems like we're not using the SSL cert that we have available when performing the discharge requests.

```
INFO:juju.client.connection:Driver connected to juju wss://10.130.48.164:17070/model/3cc37083-2e21-4548-8b43-fdd58a1d30e1/api
Traceback (most recent call last):
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.130.48.164', port=17070): Max retries exceeded with url: /auth/discharge (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/connect_current_model.py", line 27, in <module>
    loop.run(main())
  File "/home/johnsca/juju/python-libjuju/juju/loop.py", line 38, in run
    raise task.exception()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "examples/connect_current_model.py", line 17, in main
    await model.connect()
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 479, in connect
    await self._connector.connect_model(model_name)
  File "/home/johnsca/juju/python-libjuju/juju/client/connector.py", line 131, in connect_model
    bakery_client=self.bakery_client_for_controller(controller_name),
  File "/home/johnsca/juju/python-libjuju/juju/client/connector.py", line 59, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 166, in connect
    await self._connect_with_redirect([(endpoint, cacert)])
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 509, in _connect_with_redirect
    login_result = await self._connect_with_login(endpoints)
  File "/home/johnsca/juju/python-libjuju/juju/client/connection.py", line 499, in _connect_with_login
    'https://' + self.endpoint + '/',
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/macaroonbakery/httpbakery/_client.py", line 104, in handle_error
    self.key,
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/macaroonbakery/bakery/_discharge.py", line 74, in discharge_all
    dm = get_discharge(cav.cav, cav.encrypted_caveat)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/macaroonbakery/httpbakery/_client.py", line 130, in acquire_discharge
    resp = self._acquire_discharge_with_token(cav, payload, None)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/macaroonbakery/httpbakery/_client.py", line 171, in _acquire_discharge_with_token
    return self.request('POST', target, data=req, headers=headers)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/macaroonbakery/httpbakery/_client.py", line 87, in request
    return requests.request(method=method, url=url, **kwargs)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/johnsca/juju/python-libjuju/.tox/py3/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.130.48.164', port=17070): Max retries exceeded with url: /auth/discharge (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
```

**Comment by johnsca** [comment]
@rogpeppe Is this something that there's even any point to fixing?

**Comment by AdamIsrael** [comment]
I ran into this bug today, where a connection to the controller (initiated from a charm) fails unless a password is provided. 

I think this is something that does need to be addressed, or at the very least call it out in the documentation and error message surfaced to the developer. Not all production deployments are to a non-local cloud, but local is often the first experience for many users.

**Comment by johnsca** [comment]
I guess my question is whether we should hack around this by catching the cert error (I'm not even certain we can in the libjuju code), or raise this bug upstream in [pymacaroonbakery](https://github.com/go-macaroon-bakery/py-macaroon-bakery) and get it resolved there?

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
