### ISSUE TITLE
FindTagsResults seems to be broken

### ISSUE THREAD

**Issue by gnuoy** [juju/python-libjuju#241]
<tl;dr> FindTagsResults appears to be wrong but it is generated code, how should I fix it?

I have been looking to implement juju.model.get_action_status. When it is called with a prefix, the prefix needs to be resolved with a call to FindActionTagsByPrefix (from the ActionFacade). The request seems to work correctly but parsing the returned message fails:

```
Traceback (most recent call last):
  File "/tmp/test3.py", line 59, in <module>
    main()
  File "/tmp/test3.py", line 55, in main
    loop.run(deploy())
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/loop.py", line 38, in run
    raise task.exception()
  File "/tmp/test3.py", line 22, in deploy
    c = await model.get_action_status(uuid_or_prefix='0495b6ce')
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/model.py", line 1575, in get_action_status
    actions = await action_facade.FindActionTagsByPrefix([uuid_or_prefix])
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/client/facade.py", line 430, in wrapper
    print("Wrapper cls.from_json {}".format(cls.from_json(reply['response'])))
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/client/facade.py", line 557, in from_json
    return cls(**d)
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/client/_definitions.py", line 3017, in __init__
    self.matches = [Entity.from_json(o) for o in matches or []]
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/client/_definitions.py", line 3017, in <listcomp>
    self.matches = [Entity.from_json(o) for o in matches or []]
  File "/home/liam/branches/charm-vault/build/builds/vault/.tox/func-smoke/lib/python3.6/site-packages/juju/client/facade.py", line 548, in from_json
    data = json.loads(data)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)
```
In my case I am calling FindActionTagsByPrefix like this:

```action_facade.FindActionTagsByPrefix(['0495b6ce'])```

This results in FindTagsResults being called with:
```
method={'0495b6ce': [{'tag': 'action-0495b6ce-09d8-4e57-8d21-efa13794034a'}]}
```
FindTagsResults then tries to json decode the dict keys eg

``` Entity.from_json('0495b6ce')```

which explodes with the exception above.

**Comment by johnsca** [comment]
That's really odd.  It's [defined in Juju](https://github.com/juju/juju/blame/af45ac69cd96042f252b42a773c3ec238b2f6dab/apiserver/params/params.go#L34) as `Matches map[string][]Entity `json:"matches"`` but somehow got converted to `matches : typing.Sequence<+T_co>[~Entity]<~Entity>` in [`_definitions.py`](https://github.com/juju/python-libjuju/blob/master/juju/client/_definitions.py#L3010).

One thing to try is [re-syncing from upstream](https://pythonlibjuju.readthedocs.io/en/latest/upstream-updates/index.html) and see if it gets converted correctly.  That would also bring in changes from the latest Juju.

Alternatively, we could add something to [`overrides.py`](https://github.com/juju/python-libjuju/blob/master/juju/client/overrides.py) ([docs](https://pythonlibjuju.readthedocs.io/en/latest/upstream-updates/index.html#overrides)) to force it to be correct.

**Comment by johnsca** [comment]
#244 (`make client`) is fixed now.

**Comment by gnuoy** [comment]
Thanks for fixing make client. I ran it for Juju 2.3.8 and, unfortunately,  the definition of FindTagsResults did not change. I am going to go ahead and add an override.
