### ISSUE TITLE
make client fails

### ISSUE THREAD

**Issue by gnuoy** [juju/python-libjuju#244]
I attempted to run make client against tip to check it was working before updating the schema but it appears to be broken:

```
liam@figroll:~/branches/python-libjuju$ make client
.tox/py3/bin/python -m juju.client.facade -s "juju/client/schemas*" -o juju/client/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 810, in <module>
    main()
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 801, in main
    captures = generate_facades(options)
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 767, in generate_facades
    buildTypes(schema, captures[schema.version])
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 281, in buildTypes
    textwrap.indent(args.get_doc(), INDENT * 2))]
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 253, in get_doc
    return self._get_arg_str(True, "\n")
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 232, in _get_arg_str
    parts.append(self._format(item[0], item[1], typed))
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 223, in _format
    strcast(rtype)
  File "/home/liam/branches/python-libjuju/juju/client/facade.py", line 174, in strcast
    if issubclass(kind, typing.GenericMeta):
TypeError: issubclass() arg 1 must be a class
Makefile:20: recipe for target 'client' failed
make: *** [client] Error 1
```

**Comment by johnsca** [comment]
This seems to be an issue specifically with Python 3.6 and seems to be an issue with calling `issubclass` on a [`typing.TypeVar`](https://docs.python.org/3/library/typing.html#typing.TypeVar).  The docs for `TypeVar` explicitly mention that it shouldn't be used with `issubclass` with no mention of this changing from 3.5 to 3.6, so I'm not sure why it wasn't an issue previously.  Either way, we need to handle `TypeVar`s explicitly.
