### ISSUE TITLE
`scp_from` raises JujuError("command failed: %s" % cmd)

### ISSUE THREAD

**Issue by n-pochet** [juju/python-libjuju#259]
When using the `scp_from` function with `scp_opts` like in the zaza framework:
```python
await unit.scp_from(source, destination, user=user, proxy=proxy,  scp_opts=scp_opts)
```
Raises a `JujuError` exception:
```
Traceback (most recent call last):
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_tests/ceph/tests.py", line 296, in test_ceph_encryption
    scp_opts='-r -p')
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 44, in _wrapper
    return run(_run_it())
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 32, in run
    return task.result()
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/zaza/__init__.py", line 43, in _run_it
    return await f(*args, **kwargs)
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/zaza/model.py", line 226, in async_scp_from_unit
    scp_opts=scp_opts)
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/juju/unit.py", line 205, in scp_from
    proxy=proxy, scp_opts=scp_opts)
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/juju/machine.py", line 173, in scp_from
    await self._scp(source, destination, scp_opts)
  File "/home/ubuntu/ceph-osd/.tox/func-smoke/lib/python3.6/site-packages/juju/machine.py", line 192, in _scp
    raise JujuError("command failed: %s" % cmd)
juju.errors.JujuError: command failed: ['scp', '-i', '/home/ubuntu/.local/share/juju/ssh/juju_id_rsa', '-o', 'StrictHostKeyChecking=no', '-q', '-B', 'ubuntu@10.5.0.11:/etc/ceph/dmcrypt-keys', '/tmp/tmp965enr1k', '-r', '-p']
```
The error (while using the scp command directly) is:
```
scp -i /home/ubuntu/.local/share/juju/ssh/juju_id_rsa -o StrictHostKeyChecking=no -q -B ubuntu@10.5.0.11:/etc/ceph/dmcrypt-keys /tmp/tmp965enr1k -r -p
-p: No such file or directory
```
It seems that scp doesn't like to have the extra parameters where it expects the `source` and `destination`
https://github.com/juju/python-libjuju/blob/26c86c81f763acae352478ff77bdc97cd5469299/juju/machine.py#L175-L192
Could be modified into something like:
```python
cmd = ['scp']
cmd += scp_opts.split()
cmd.extend([
            '-i', os.path.expanduser('~/.local/share/juju/ssh/juju_id_rsa'),
            '-o', 'StrictHostKeyChecking=no',
            '-q',
            '-B',
            source, destination
        ])
```

**Comment by johnsca** [comment]
This is released in 0.10.0
