### ISSUE TITLE
JujuConnectionError Unable to connect to any endpoint

### ISSUE THREAD

**Issue by kwmonroe** [juju/python-libjuju#289]
I'm having controller connection errors from libjuju when using conjure-up (latest 2.6.5 with libjuju 0.11.2). I have the most success in repro'ing with the cdk bundle + graylog + prometheus addons.

Here's a snippet of the relevant log showing the failure:
```
2019-02-02 08:10:37,116 [INFO] conjure-up/canonical-kubernetes - common.py:47 - Waiting for deployment to settle.
2019-02-02 08:13:58,162 [WARNING] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:227 - Receiver: Connection closed, reconnecting
2019-02-02 08:13:58,234 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2019-02-02 08:13:58,234 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<Connection.reconnect() done, defined at /usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py:424> exception=JujuConnectionError('Unable to connect to any endpoint: 54.193.104.241:17070')>
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 432, in reconnect
    await self._connect_with_login([(self.endpoint, self.cacert)])
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 478, in _connect_with_login
    await self._connect(endpoints)
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 458, in _connect
    endpoint for endpoint, cacert in endpoints])))
juju.errors.JujuConnectionError: Unable to connect to any endpoint: 54.193.104.241:17070
```

I had hoped that @johnsca's recent PR to include a connection retry might help (https://github.com/juju/python-libjuju/pull/288), but it didn't.  Here's another snippet with the new libjuju code + debug:
```
2019-02-02 11:14:30,233 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:898 - client > Frame(fin=True, opcode=1, data=b'{\n  "type": "Pinger",\n  "request": "Ping",\n  "version": 1,\n  "params": {},\n  "request-id": 1411\n}', rsv1=False, rsv2=False, rsv3=False)
2019-02-02 11:14:30,297 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:886 - client < Frame(fin=True, opcode=1, data=b'{"request-id":1411,"response":{}}\n', rsv1=False, rsv2=False, rsv3=False)
2019-02-02 11:14:30,297 [DEBUG] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:319 - connection 4578697512 <- {'request-id': 1411, 'response': {}}
2019-02-02 11:14:31,396 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1220 - client - event = eof_received()
2019-02-02 11:14:31,397 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1113 - client ! failing WebSocket connection in the OPEN state: 1006 [no reason]
2019-02-02 11:14:31,397 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1229 - client - event = connection_lost(None)
2019-02-02 11:14:31,397 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1231 - client - state = CLOSED
2019-02-02 11:14:31,397 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1238 - client x code = 1006, reason = [no reason]
2019-02-02 11:14:31,398 [WARNING] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:237 - Receiver: Connection closed, reconnecting
2019-02-02 11:14:31,398 [DEBUG] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:1053 - client x closing TCP connection
2019-02-02 11:14:31,466 [DEBUG] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:473 - Retrying connection to endpoints: 54.193.104.241:17070; attempt 1 of 4
2019-02-02 11:14:41,468 [DEBUG] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:473 - Retrying connection to endpoints: 54.193.104.241:17070; attempt 2 of 4
2019-02-02 11:15:01,469 [DEBUG] conjure-up/canonical-kubernetes - juju.client.connection: connection.py:473 - Retrying connection to endpoints: 54.193.104.241:17070; attempt 3 of 4
2019-02-02 11:15:31,472 [DEBUG] conjure-up/canonical-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2019-02-02 11:15:31,473 [ERROR] conjure-up/canonical-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<Connection.reconnect() done, defined at /usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py:434> exception=JujuConnectionError('Unable to connect to any endpoint: 54.193.104.241:17070')>
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 442, in reconnect
    await self._connect_with_login([(self.endpoint, self.cacert)])
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 502, in _connect_with_login
    await self._connect(endpoints)
  File "/usr/local/Cellar/conjure-up/2.6.5/libexec/lib/python3.7/site-packages/juju/client/connection.py", line 479, in _connect
    '{}'.format(_endpoints_str))
juju.errors.JujuConnectionError: Unable to connect to any endpoint: 54.193.104.241:17070
```

I'll attach the full debug log and look for something simpler than a conjure-up repro scenario.

One thing that worries me is that in all failing cases, conjure-up post deployment steps actually finish -- it's only when i leave the final result screen up for 2-10 minutes that it eventually fails. Maybe this points to conjure-up (or a spell step) doing something wrong instead of libjuju.

**Comment by kwmonroe** [comment]
Full conjure-up debug log from a failing case:
[conjure-up.log](https://github.com/juju/python-libjuju/files/2825165/conjure-up.log)
