### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 3)

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#292]
Originally reported here: https://github.com/conjure-up/conjure-up/issues/1591

libjuju started failing to deploy bundles with Juju 2.5.2

```python-traceback
[gw0] linux -- Python 3.6.7 /home/johnsca/juju/python-libjuju/.tox/py3/bin/python
Traceback (most recent call last):
  File "/home/johnsca/juju/python-libjuju/tests/integration/test_model.py", line 88, in test_deploy_bundle
    await model.deploy('bundle/wiki-simple')
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 1283, in deploy
    await handler.execute_plan()
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 1966, in execute_plan
    result = await method(*step.args)
  File "/home/johnsca/juju/python-libjuju/juju/model.py", line 2127, in deploy
    devices, resources, num_units, placement = args
ValueError: not enough values to unpack (expected 4, got 3)
==================================================================================================== short test summary info ====================================================================================================
FAILED tests/integration/test_model.py::test_deploy_bundle
```

This succeeds on 2.5.1

```
[gw2] PASSED tests/integration/test_model.py::test_deploy_bundle 
```

**Comment by johnsca** [comment]
I think this may have been caused by https://github.com/juju/bundlechanges/pull/48

**Comment by johnsca** [comment]
@wallyworld @ycliuhw  Can one of you guys take a look at this?
