### ISSUE TITLE
ambiguous constraints: "cores" overlaps with "instance-type"'

### ISSUE THREAD

**Issue by dannf** [juju/python-libjuju#341]
As an attempt at working around #333 I switched to the juju edge channel (2.7-beta1+develop-6c8272e). While I can deploy charms from the command line, it is now failing via python-juju (2.6.0):
```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from juju.controller import Controller
>>> import asyncio
>>> async def main():
...     controller = Controller()
...     await controller.connect()
...     model = await controller.add_model('pyjuju')
...     app = await model.deploy('ubuntu', constraints={'arch': 'amd64'})
... 
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "<stdin>", line 5, in main
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1431, in deploy
    devices=devices,
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1508, in _deploy
    result = await app_facade.Deploy(applications=[app])
  File "/usr/local/lib/python3.6/dist-packages/juju/client/facade.py", line 423, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/_client8.py", line 751, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/facade.py", line 548, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/connection.py", line 472, in rpc
    raise errors.JujuError(err_results)
juju.errors.JujuError: ['cannot add application "ubuntu": ambiguous constraints: "cores" overlaps with "instance-type"']
```

**Comment by mitechie** [comment]
Hmm, cores is intended to be cloud agnostic while instance types aren't. While it's true that they can overlap, I believe we rely on instance-type being more specific and winning. Can I ask what you attempted to do and what you expected to have happen? Maybe we can do better at managing the expectations there?

**Comment by dannf** [comment]
As an attempt at working around #333 I switched to the juju edge channel (2.7-beta1+develop-6c8272e). While I can deploy charms from the command line, it is now failing via python-juju (2.6.0):
```
$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from juju.controller import Controller
>>> import asyncio
>>> async def main():
...     controller = Controller()
...     await controller.connect()
...     model = await controller.add_model('pyjuju')
...     app = await model.deploy('ubuntu', constraints={'arch': 'amd64'})
... 
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "<stdin>", line 5, in main
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1431, in deploy
    devices=devices,
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1508, in _deploy
    result = await app_facade.Deploy(applications=[app])
  File "/usr/local/lib/python3.6/dist-packages/juju/client/facade.py", line 423, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/_client8.py", line 751, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/facade.py", line 548, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.6/dist-packages/juju/client/connection.py", line 472, in rpc
    raise errors.JujuError(err_results)
juju.errors.JujuError: ['cannot add application "ubuntu": ambiguous constraints: "cores" overlaps with "instance-type"']
```

**Comment by mitechie** [comment]
Interesting, so it's not so much both were asked for but some innate issue there. We'll look into it.

**Comment by mitechie** [comment]
One thing to suggest, for working around issue 333 is that there's a candidate snap up that's in QA testing at the moment we will be looking to release next week. It should unblock your current work to switch to the 2.6/candidate channel while we chase down why the constraint issue popped up with 2.7.

**Comment by dannf** [comment]
@mitechie thanks for the suggestion! Unfortunately, this issue seems to impact 2.6/candidate, and every other version I've tried except for xenial's. Note: things work fine if I remove the arch constraint from the deploy. Obviously I don't need that for amd64 - but multi-architecture is a requirement.

**Comment by SimonRichardson** [comment]
@dannf I'm looking into this now and hopefully get a quick turn around on this.
