### ISSUE TITLE
Generating facades from schema fails with python 3.7

### ISSUE THREAD

**Issue by SimonRichardson** [juju/python-libjuju#377]
Unfortunately python3.7 broke compatibility between python3.6 and python3.7 when introspecting types for generating the facades.

Attempting to updating it requires some significant changes to pylibjuju.

See:

```
➜ make client
.tox/py3/bin/python3.7 -m juju.client.facade -s "juju/client/schemas*" -o juju/client/
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/simon/Documents/python-libjuju/juju/client/facade.py", line 895, in <module>
    main()
  File "/home/simon/Documents/python-libjuju/juju/client/facade.py", line 885, in main
    definitions = generate_definitions(schemas)
  File "/home/simon/Documents/python-libjuju/juju/client/facade.py", line 824, in generate_definitions
    buildTypes(schema, definitions)
  File "/home/simon/Documents/python-libjuju/juju/client/facade.py", line 387, in buildTypes
    elif issubclass(arg_type, typing.Sequence):
  File "/usr/lib/python3.7/typing.py", line 719, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
make: *** [Makefile:16: client] Error 1
```

**Comment by SimonRichardson** [comment]
This was fixed by @hpidcock for #412
