### ISSUE TITLE
VERSION not included in pypi package

### ISSUE THREAD

**Issue by simonklb** [juju/python-libjuju#38]
```
$ pip install juju
Collecting juju
  Downloading juju-0.1.0.tar.gz (115kB)
    100% |████████████████████████████████| 122kB 3.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g2u8_xcm/juju/setup.py", line 24, in <module>
        version=version.read_text().strip(),
      File "/usr/lib/python3.5/pathlib.py", line 1164, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/lib/python3.5/pathlib.py", line 1151, in open
        opener=self._opener)
      File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
        return self._accessor.open(self, flags, mode)
      File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
        return strfunc(str(pathobj), *args)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-g2u8_xcm/juju/VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g2u8_xcm/juju/
```

**Comment by tvansteenburgh** [comment]
D'oh! The last-minute addition strikes again. Will fix and update asap.
