### ISSUE TITLE
directive replace not exist

### ISSUE THREAD

**Issue by redno2** [juju/python-libjuju#428]
There is an error when I try to deploy my bundle. It try to replace string that doesn't exist.

I use your code : https://github.com/juju/python-libjuju/blob/master/examples/deploy_bundle.py
And just replace by my local bundle like;
```       
 applications = await model.deploy(
            "/..../bundle.yaml",
        )
```

```
python3 juju-bvt-deploy.py 
Connecting to model
WARNING:juju.client.connection:unknown facade CAASModelOperator
WARNING:juju.client.connection:unexpected facade CAASModelOperator found, unable to decipher version to use
WARNING:juju.model:unknown delta type: id
Deploying bundle
INFO:juju.bundle:Applying change: upload charm cs:~containers/canal-726 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/kubeapi-load-balancer-730 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/kubernetes-master-850 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/kubernetes-worker-682 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/containerd-80 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/easyrsa-318 for series bionic
INFO:juju.bundle:Applying change: upload charm cs:~containers/etcd-521 for series bionic
INFO:juju.bundle:Applying change: deploy application canal with 0 unit on bionic using $addCharm-0
INFO:juju.model:Deploying cs:~containers/canal-726
INFO:juju.bundle:Applying change: deploy application etcd with 0 unit on bionic using $addCharm-9
INFO:juju.model:Deploying cs:~containers/etcd-521
INFO:juju.bundle:Applying change: deploy application kubeapi-load-balancer with 0 unit on bionic using $addCharm-12
INFO:juju.model:Deploying cs:~containers/kubeapi-load-balancer-730
INFO:juju.bundle:Applying change: deploy application kubernetes-master with 0 unit on bionic using $addCharm-16
INFO:juju.model:Deploying cs:~containers/kubernetes-master-850
INFO:juju.bundle:Applying change: deploy application kubernetes-worker with 0 unit on bionic using $addCharm-19
INFO:juju.model:Deploying cs:~containers/kubernetes-worker-682
INFO:juju.bundle:Applying change: deploy application containerd with 0 unit on bionic using $addCharm-3
INFO:juju.model:Deploying cs:~containers/containerd-80
INFO:juju.bundle:Applying change: deploy application easyrsa with 0 unit on bionic using $addCharm-6
INFO:juju.model:Deploying cs:~containers/easyrsa-318
INFO:juju.bundle:Applying change: add relation $deploy-17:kube-api-endpoint - $deploy-13:apiserver
INFO:juju.bundle:Relating kubernetes-master:kube-api-endpoint <-> kubeapi-load-balancer:apiserver
INFO:juju.bundle:Applying change: add relation $deploy-17:loadbalancer - $deploy-13:loadbalancer
INFO:juju.bundle:Relating kubernetes-master:loadbalancer <-> kubeapi-load-balancer:loadbalancer
INFO:juju.bundle:Applying change: add relation $deploy-17:kube-control - $deploy-20:kube-control
INFO:juju.bundle:Relating kubernetes-master:kube-control <-> kubernetes-worker:kube-control
INFO:juju.bundle:Applying change: add relation $deploy-17:certificates - $deploy-7:client
INFO:juju.bundle:Relating kubernetes-master:certificates <-> easyrsa:client
INFO:juju.bundle:Applying change: add relation $deploy-10:certificates - $deploy-7:client
INFO:juju.bundle:Relating etcd:certificates <-> easyrsa:client
INFO:juju.bundle:Applying change: add relation $deploy-17:etcd - $deploy-10:db
INFO:juju.bundle:Relating kubernetes-master:etcd <-> etcd:db
INFO:juju.bundle:Applying change: add relation $deploy-20:certificates - $deploy-7:client
INFO:juju.bundle:Relating kubernetes-worker:certificates <-> easyrsa:client
INFO:juju.bundle:Applying change: add relation $deploy-20:kube-api-endpoint - $deploy-13:website
INFO:juju.bundle:Relating kubernetes-worker:kube-api-endpoint <-> kubeapi-load-balancer:website
INFO:juju.bundle:Applying change: add relation $deploy-13:certificates - $deploy-7:client
INFO:juju.bundle:Relating kubeapi-load-balancer:certificates <-> easyrsa:client
INFO:juju.bundle:Applying change: add relation $deploy-1:etcd - $deploy-10:db
INFO:juju.bundle:Relating canal:etcd <-> etcd:db
INFO:juju.bundle:Applying change: add relation $deploy-1:cni - $deploy-17:cni
INFO:juju.bundle:Relating canal:cni <-> kubernetes-master:cni
INFO:juju.bundle:Applying change: add relation $deploy-1:cni - $deploy-20:cni
INFO:juju.bundle:Relating canal:cni <-> kubernetes-worker:cni
INFO:juju.bundle:Applying change: add relation $deploy-4:containerd - $deploy-20:container-runtime
INFO:juju.bundle:Relating containerd:containerd <-> kubernetes-worker:container-runtime
INFO:juju.bundle:Applying change: add relation $deploy-4:containerd - $deploy-17:container-runtime
INFO:juju.bundle:Relating containerd:containerd <-> kubernetes-master:container-runtime
INFO:juju.bundle:Applying change: add $deploy-17 unit to None
INFO:juju.bundle:Applying change: add $deploy-20 unit to None
INFO:juju.bundle:Applying change: expose $deploy-13
INFO:juju.bundle:Exposing kubeapi-load-balancer
INFO:juju.bundle:Applying change: expose $deploy-20
INFO:juju.bundle:Exposing kubernetes-worker
INFO:juju.bundle:Applying change: set annotations for $deploy-10
INFO:juju.bundle:Applying change: set annotations for $deploy-13
INFO:juju.bundle:Applying change: set annotations for $deploy-17
INFO:juju.bundle:Applying change: set annotations for $deploy-1
INFO:juju.bundle:Applying change: set annotations for $deploy-20
INFO:juju.bundle:Applying change: set annotations for $deploy-4
INFO:juju.bundle:Applying change: set annotations for $deploy-7
INFO:juju.bundle:Applying change: add lxd container on new machine
INFO:juju.bundle:Applying change: add $deploy-10 unit to $addUnit-40
Disconnecting from model
Success
Traceback (most recent call last):
  File "juju-bvt-deploy.py", line 96, in <module>
    loop.run(main())
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/loop.py", line 38, in run
    raise task.exception()
  File "juju-bvt-deploy.py", line 90, in main
    await deploy_bundle()
  File "juju-bvt-deploy.py", line 60, in deploy_bundle
    "/home/rpretot/Devel/cloud-cdk/deploy/non-prod/bvt-bank-gl/bundle.yaml",
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/model.py", line 1394, in deploy
    await handler.execute_plan()
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/bundle.py", line 153, in execute_plan
    self.references[step.id_] = await change.run(self)
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/bundle.py", line 628, in run
    to=placement,
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/application.py", line 125, in add_unit
    placement=parse_placement(to) if to else None,
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/placement.py", line 28, in parse
    results.extend(parse(d))
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/placement.py", line 37, in parse
    directive = directive.replace('lxc', 'lxd')
  File "/home/rpretot/.local/lib/python3.6/site-packages/juju/model.py", line 273, in __getattr__
    return self.safe_data[name]
KeyError: 'replace'
```

My bundle :
```
description: Build verification test models
series: bionic
services:
  canal:
    annotations:
      gui-x: '475'
      gui-y: '605'
    bindings:
      cni: k8s-internal-space
      '': k8s-provisioning-space
    charm: cs:~containers/canal-726
    options:
      cidr: 10.10.0.0/16
    resources:
      calico: 658
      calico-arm64: 659
      calico-node-image: 343
      calico-upgrade: 476
      calico-upgrade-arm64: 479
      flannel: 656
      flannel-arm64: 659
  containerd:
    annotations:
      gui-x: '475'
      gui-y: '800'
    charm: cs:~containers/containerd-80
    http_proxy: http://123.123.123.123:8080
    https_proxy: http://123.123.123.123:8080
    no_proxy: 127.0.0.1,localhost,.sub.domain.com,.sub2.domain.com,*.sub.domain.com,*.sub2.domain.com,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.*,192.*,172.*
    resources: {}
  easyrsa:
    annotations:
      gui-x: '90'
      gui-y: '420'
    bindings:
      '': k8s-provisioning-space
    charm: cs:~containers/easyrsa-318
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
    to:
    - lxd:kubernetes-master
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '420'
    bindings:
      cluster: k8s-internal-space
      db: k8s-internal-space
      '': k8s-provisioning-space
    charm: cs:~containers/etcd-521
    constraints: root-disk=8G
    num_units: 1
    options:
      channel: 3.2/stable
      snap_proxy: http://123.123.123.123:8000
    resources:
      core: 0
      etcd: 3
      snapshot: 0
    to:
    - kubernetes-master
  kubeapi-load-balancer:
    annotations:
      gui-x: '450'
      gui-y: '250'
    bindings:
      website: k8s-provisioning-space
    charm: cs:~containers/kubeapi-load-balancer-730
    constraints: mem=4G root-disk=8G
    expose: true
    num_units: 1
    resources: {}
    to:
    - kubernetes-master
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    bindings:
      kube-api-endpoint: k8s-provisioning-space
      kube-control: k8s-internal-space
      '': k8s-provisioning-space
    charm: cs:~containers/kubernetes-master-850
    constraints: tags=virtual,k8s,bvt
    num_units: 1
    options:
      allow-privileged: 'true'
      api-extra-args: oidc-issuer-url=https://bob.sub.domain.com/dex oidc-client-id=pre-k8s oidc-username-claim=email oidc-groups-claim=groups
      authorization-mode: Node,RBAC
      channel: 1.18/stable
      enable-dashboard-addons: true
      snap_proxy: http://123.123.123.123:8000
      snapd_refresh: fri5,23:00
    resources:
      cdk-addons: 0
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
  kubernetes-worker:
    annotations:
      gui-x: '90'
      gui-y: '850'
    bindings:
      kube-control: k8s-internal-space
      '': k8s-dmz-space
    charm: cs:~containers/kubernetes-worker-682
    constraints: tags=virtual,k8s,bvt
    expose: true
    num_units: 2
    options:
      allow-privileged: 'true'
      channel: 1.18/stable
      ingress: 'False'
      snap_proxy: http://123.123.123.123:8000
      snapd_refresh: fri5,23:00
    resources:
      cni-amd64: 645
      cni-arm64: 636
      cni-s390x: 648
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - canal:etcd
  - etcd:db
- - canal:cni
  - kubernetes-master:cni
- - canal:cni
  - kubernetes-worker:cni
- - containerd:containerd
  - kubernetes-worker:container-runtime
- - containerd:containerd
  - kubernetes-master:container-runtime


```

Thanks

**Comment by redno2** [comment]
any input ?

**Comment by SimonRichardson** [comment]
I can replicate it with a smaller bundle...

```yaml
series: bionic
applications:
  canal:
    charm: "cs:~containers/canal-726"
    resources:
      calico: 658
      calico-arm64: 659
      calico-node-image: 343
      calico-upgrade: 476
      calico-upgrade-arm64: 479
      flannel: 656
      flannel-arm64: 659
  containerd:
    charm: "cs:~containers/containerd-80"
    resources: {}
  easyrsa:
    charm: "cs:~containers/easyrsa-318"
    constraints: root-disk=8G
    num_units: 1
    resources:
      easyrsa: 5
    to:
      - "lxd:kubernetes-master"
  etcd:
    annotations:
    charm: "cs:~containers/etcd-521"
    constraints: root-disk=8G
    num_units: 1
    options:
      channel: 3.2/stable
    resources:
      core: 0
      etcd: 3
      snapshot: 0
    to:
      - kubernetes-master
  kubeapi-load-balancer:
    charm: "cs:~containers/kubeapi-load-balancer-730"
    constraints: mem=4G root-disk=8G
    expose: true
    num_units: 1
    resources: {}
    to:
      - kubernetes-master
  kubernetes-master:
    charm: "cs:~containers/kubernetes-master-850"
    constraints: "tags=virtual,k8s,bvt"
    num_units: 1
    options:
      allow-privileged: "true"
      api-extra-args: >-
        oidc-issuer-url=https://bob.sub.domain.com/dex oidc-client-id=pre-k8s
        oidc-username-claim=email oidc-groups-claim=groups
      authorization-mode: "Node,RBAC"
      channel: 1.18/stable
      enable-dashboard-addons: true
    resources:
      cdk-addons: 0
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
  kubernetes-worker:
    charm: "cs:~containers/kubernetes-worker-682"
    constraints: "tags=virtual,k8s,bvt"
    expose: true
    num_units: 2
    options:
      allow-privileged: "true"
      channel: 1.18/stable
      ingress: "False"
    resources:
      cni-amd64: 645
      cni-arm64: 636
      cni-s390x: 648
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
relations:
- - "kubernetes-master:kube-api-endpoint"
  - "kubeapi-load-balancer:apiserver"
- - "kubernetes-master:loadbalancer"
  - "kubeapi-load-balancer:loadbalancer"
- - "kubernetes-master:kube-control"
  - "kubernetes-worker:kube-control"
- - "kubernetes-master:certificates"
  - "easyrsa:client"
- - "etcd:certificates"
  - "easyrsa:client"
- - "kubernetes-master:etcd"
  - "etcd:db"
- - "kubernetes-worker:certificates"
  - "easyrsa:client"
- - "kubernetes-worker:kube-api-endpoint"
  - "kubeapi-load-balancer:website"
- - "kubeapi-load-balancer:certificates"
  - "easyrsa:client"
- - "canal:etcd"
  - "etcd:db"
- - "canal:cni"
  - "kubernetes-master:cni"
- - "canal:cni"
  - "kubernetes-worker:cni"
- - "containerd:containerd"
  - "kubernetes-worker:container-runtime"
- - "containerd:containerd"
  - "kubernetes-master:container-runtime"
```

**Comment by SimonRichardson** [comment]
So the reason why this doens't work is because pylibjuju isn't aware what to do when you have a placement directive of: 

```yaml
applications:
...
    etcd:
    ....
        to:
          - kubernetes-master
...
    kubernetes-master:

```

The placement thinks it should try and place it on a unit @wallyworld might know what to do here.

**Comment by SimonRichardson** [comment]
@redno2 I don't believe the placement directive is correct here. I think the fix is for pylibjuju to have a better error message to indicate why it failed.

**Comment by juanmanuel-tirado** [comment]
This issue is expired. Reopen if required.
