### ISSUE TITLE
'pip install juju' keeps failing

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#52]
Everytime I want to install the JUJU pip package(`pip install juju`) it fails and I get the following error:

```
Collecting juju
  Downloading juju-0.1.2.tar.gz (127kB)
    100% |████████████████████████████████| 133kB 935kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-N2anhR/juju/setup.py", line 24, in <module>
        version=version.read_text().strip(),
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-N2anhR/juju/
```

I already updated all my other packages but I still got the error. Is there any package still missing or do I need to downgrade a certain package?

**Comment by tvansteenburgh** [comment]
Are you using Python 3.5+?

**Comment by sebastienpattyn93** [comment]
I'm using Python 3.5.2 but Python 2.7.12 is installed as well. Using `pip3 install juju` fixed the problem. Thank you.
