### ISSUE TITLE
Infinite loop connecting to model - lack of error message

### ISSUE THREAD

**Issue by dasm** [juju/python-libjuju#523]
When I tried to connect to a model, it gets stuck in infinite loop. ([1])

```python
>>> from juju.model import Model
>>> from juju.loop import run
>>> model = Model()
>>> run(model.connect("openstack"))
RPC: Connection closed, reconnecting
RPC: Connection closed, reconnecting
Receiver: Connection closed, reconnecting
RPC: Automatic reconnect failed
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jujumanage/jujubackupall_packages/juju/loop.py", line 36, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
>>> import logging
>>> logging.basicConfig(level="DEBUG")
>>> run(model.connect("openstack"))
DEBUG:juju.model:Closing model connection
DEBUG:connector:Closing model connection
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=9, data=b'>M\\\x9e', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - state = CLOSING
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = data_received(<6 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=10, data=b'>M\\\x9e', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - received solicited pong: 3e4d5c9e
DEBUG:websockets.protocol:client - event = data_received(<4 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client - event = connection_lost(None)
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1000, reason = [no reason]
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:websockets.protocol:client - state = CONNECTING
DEBUG:websockets.protocol:client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7f1306f9ba60>)
DEBUG:websockets.client:client > GET /model/666cbd0e-58a4-4951-8b75-9b5ca9733f2f/api HTTP/1.1
DEBUG:websockets.client:client > Headers([('Host', '10.130.12.22:17070'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', '7QCqLYU1bg1oYYPGxzH1XQ=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
DEBUG:websockets.protocol:client - event = data_received(<129 bytes>)
DEBUG:websockets.client:client < HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:client < Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'hgAX4ZRiUg5gA0oxzqq8ZTb03VM=')])
DEBUG:websockets.protocol:client - state = OPEN
DEBUG:juju.client.connection:Driver connected to juju wss://10.130.12.22:17070/model/666cbd0e-58a4-4951-8b75-9b5ca9733f2f/api
```

After stripping down all layers of the library ([2]) I found that it gets stuck on `asyncio.wait([task])`.

```python
import logging
import asyncio

from juju.model import Model
from juju.loop import run

from juju.client import client
from juju import utils

FORMAT = "%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] %(name)s %(message)s"
logging.basicConfig(format=FORMAT, level="DEBUG")

model = Model()
# run(model.connect("openstack"))
run(model._connector.connect_model("openstack"))
# run(model._after_connect())
# run(model._watch())

logging.debug("Starting watcher task")
model._watch_received.clear()
model._watch_stopping.clear()
model._watch_stopped.clear()

# run(model._connector.loop.create_task(_all_watcher()))
model_config = run(model.get_config())
if "mode" in model_config:
    mode = model_config["mode"]["value"]
    print(mode)
    model._mode = mode

allwatcher = client.AllWatcherFacade.from_connection(model.connection())

# results = run(utils.run_with_interrupt(allwatcher.Next(), model._watch_stopping, loop=model._connector.loop))
loop = model._connector.loop
task = asyncio.ensure_future(allwatcher.Next(), loop=model._connector.loop)
event_tasks = [loop.create_task(event.wait()) for event in [model._watch_stopping]]
done, pending = run(asyncio.wait([task]+event_tasks, loop=loop, return_when=asyncio.FIRST_COMPLETED))
```

In logs ([3]) it can be seen that an exception `PayloadTooBig` is raised
```python
2021-08-23 18:22:05,986 ERROR [base_events.py:1707] asyncio Task exception was never retrieved
future: <Task finished name='Task-26' coro=<AllWatcherFacade.Next() done, defined at /home/jujumanage/jujubackupall_packages/juju/client/facade.py:477> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason')>
Traceback (most recent call last):
  File "/home/jujumanage/jujubackupall_packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/jujumanage/jujubackupall_packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/jujumanage/jujubackupall_packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/jujumanage/jujubackupall_packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/jujumanage/jujubackupall_packages/websockets/framing.py", line 126, in read
    raise PayloadTooBig(
websockets.exceptions.PayloadTooBig: payload length exceeds size limit (19491126 > 4194304 bytes)
```
After playing a while with ([4]), I was successfully able to get it working (`def connect` doesn't accept `max_frame_size` as mentioned in docs ([5])):
```python
>>> from juju.model import Model
>>> from juju.loop import run
>>> model = Model()
>>> run(model.connect(model_name="openstack", max_frame_size=19491127))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jujumanage/jujubackupall_packages/juju/loop.py", line 38, in run
    raise task.exception()
  File "/home/jujumanage/jujubackupall_packages/juju/model.py", line 547, in connect
    await self._connector.connect_model(model_name, **kwargs)
TypeError: connect_model() got an unexpected keyword argument 'max_frame_size'
>>> model = Model(max_frame_size=19491127)
>>> run(model.connect("openstack"))
>>> 
```

[1]: https://pastebin.canonical.com/p/BvBfdCDgWd/
[2]: https://pastebin.canonical.com/p/yz787xWcPS/
[3]: https://pastebin.canonical.com/p/SVQH3Q2sf4/
[4]: https://github.com/juju/python-libjuju/blob/master/juju/model.py#L433
[5]: https://github.com/juju/python-libjuju/blob/master/juju/model.py#L536

**Comment by cderici** [comment]
This should be fixed by https://github.com/juju/python-libjuju/commit/8a037110bede2bc40e95d7096ce1cc19c66c429b , @dasm  can you confirm?
