### ISSUE TITLE
Model `connect` doesn't allow for `max_frame_size`

### ISSUE THREAD

**Issue by dasm** [juju/python-libjuju#524]
Based on the documentation ([1]), one of allowed parameters is `max_frame_size`. After providing it as keyword, I got an error

```python
>>> from juju.model import Model
>>> from juju.loop import run
>>> model = Model()
>>> run(model.connect(model_name="openstack", max_frame_size=19491127))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jujumanage/jujubackupall_packages/juju/loop.py", line 38, in run
    raise task.exception()
  File "/home/jujumanage/jujubackupall_packages/juju/model.py", line 547, in connect
    await self._connector.connect_model(model_name, **kwargs)
TypeError: connect_model() got an unexpected keyword argument 'max_frame_size'
>>> model = Model(max_frame_size=19491127)
>>> run(model.connect("openstack"))
>>> 
```

[1]: https://pythonlibjuju.readthedocs.io/en/latest/api/juju.model.html?highlight=def%20connect#juju.model.Model.connect

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Patch some missing arguments in python-libjuju](https://trello.com/c/d7oTonYt/3906-patch-some-missing-arguments-in-python-libjuju)
