### ISSUE TITLE
connect_current fails ugly if you have a non-admin account with password

### ISSUE THREAD

**Issue by mitechie** [juju/python-libjuju#53]
I'm connecting to MAAS with a non-admin controller account. The account is the result of an add-user and register and has a custom password. 

This should catch and output something a bit nicer if possible, or sanity check and fail in a clear way. 

I added a password to `.local/share/juju/accounts.yaml` and it worked out. 

It'd also be nice, since this is a common multi-user scenario, to allow connect_current to accept some flags so that I don't have to fill in all the info but I can supply a password/etc. I guess I'd like some way to setup a cli script to allow the user to specify some info via shortcut (what controller/model via cli args) and then supply stuff like passwords in some clean way (env var?)

Failure:

    Connecting to model
    Traceback (most recent call last):
      File "stressjuju/stressjuju.py", line 39, in <module>
        loop.run(main())
      File "/home/rharding/src/jujutest/python-libjuju/juju/loop.py", line 31, in run
        raise task.exception()
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "stressjuju/stressjuju.py", line 16, in main
        await model.connect_current()
      File "/home/rharding/src/jujutest/python-libjuju/juju/model.py", line 395, in connect_current
        self.connection = await connection.Connection.connect_current()
      File "/home/rharding/src/jujutest/python-libjuju/juju/client/connection.py", line 222, in connect_current
        '{}:{}'.format(controller_name, model_name))
      File "/home/rharding/src/jujutest/python-libjuju/juju/client/connection.py", line 274, in connect_model
        endpoint, model_uuid, username, password, cacert, macaroons)
      File "/home/rharding/src/jujutest/python-libjuju/juju/client/connection.py", line 186, in connect
        await client.login(username, password, macaroons)
      File "/home/rharding/src/jujutest/python-libjuju/juju/client/connection.py", line 297, in login
        "macaroons": macaroons or []
      File "/home/rharding/src/jujutest/python-libjuju/juju/client/connection.py", line 95, in rpc
        raise JujuAPIError(result)
    juju.errors.JujuAPIError: no credentials provided
    Task was destroyed but it is pending!
    task: <Task pending coro=<WebSocketCommonProtocol.run() running at /home/rharding/src/jujutest/.venv/lib/python3.5/site-packages/websockets/protocol.py:413> wait_for=<Future pending cb=[Task._wakeup()]>>
    Fatal write error on socket transport
    protocol: <asyncio.sslproto.SSLProtocol object at 0x7fad895c0eb8>
    transport: <_SelectorSocketTransport fd=6>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
        n = self._sock.send(data)
    OSError: [Errno 9] Bad file descriptor
    Fatal error on SSL transport
    protocol: <asyncio.sslproto.SSLProtocol object at 0x7fad895c0eb8>
    transport: <_SelectorSocketTransport closing fd=6>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 700, in write
        n = self._sock.send(data)
    OSError: [Errno 9] Bad file descriptor

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/sslproto.py", line 632, in _process_write_backlog
        self._transport.write(chunk)
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 704, in write
        self._fatal_error(exc, 'Fatal write error on socket transport')
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 589, in _fatal_error
        self._force_close(exc)
      File "/usr/lib/python3.5/asyncio/selector_events.py", line 601, in _force_close
        self._loop.call_soon(self._call_connection_lost, exc)
      File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
        handle = self._call_soon(callback, args)
      File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
        self._check_closed()
      File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed

**Comment by juanmanuel-tirado** [comment]
This issue is five years old.
