### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by cderici** [juju/python-libjuju#604]
An intermittent failure we see in the CI integration tests. Likely happens during the RPC for the facade call.

```python
_________________________________ test_consume _________________________________
[gw14] linux -- Python 3.6.9 /home/ubuntu/go/src/github.com/juju/python-libjuju/.tox/py3/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/go/src/github.com/juju/python-libjuju/.tox/py3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ubuntu/go/src/github.com/juju/python-libjuju/.tox/py3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ubuntu/go/src/github.com/juju/python-libjuju/.tox/py3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

The currently known tests that exhibit this exact same failure are:

* `test_consume`
* `test_deploy_local_bundle_dir`
* `test_deploy_local_bundle_include_base64`
* `test_remove_saas`
* `test_expose_unexpose`

**Comment by SimonRichardson** [comment]
This is a bug in Juju because Juju isn't sending a control frame without a status, which causes all the clients to error out. See https://bugs.launchpad.net/juju/+bug/1961192

**Comment by juanmanuel-tirado** [comment]
According to the comments this is an issue on the juju side not python-libjuju itself. I will close it.
