### ISSUE TITLE
application refresh (upgrade charm) fails with ConnectionResetError

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#606]
The [upgrade_charm](https://pythonlibjuju.readthedocs.io/en/latest/api/juju.application.html#juju.application.Application.upgrade_charm) function fails, but upgrading via cli [works fine](https://github.com/canonical/alertmanager-k8s-operator/pull/50).

```
Traceback (most recent call last):
  File "/home/ubuntu/cos/alertmanager-k8s-operator/tests/integration/test_upgrade_charm.py", line 43, in test_build_and_deploy
    await ops_test.model.applications[app_name].refresh(path=local_charm, resources=resources)
  File "/home/ubuntu/cos/alertmanager-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/application.py", line 628, in refresh
    await self.local_refresh(channel, force, force_series, force_units,
  File "/home/ubuntu/cos/alertmanager-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/application.py", line 764, in local_refresh
    charm_url = await self.model.add_local_charm_dir(charm_dir, series)
  File "/home/ubuntu/cos/alertmanager-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/model.py", line 799, in add_local_charm_dir
    charm_url = await loop.run_in_executor(None, func)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/cos/alertmanager-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/model.py", line 829, in add_local_charm
    conn.request("POST", path, charm_file, headers)
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1047, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.9/http/client.py", line 969, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.9/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.9/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by cderici** [comment]
After investigating this a bit, I couldn't find any obvious reasons on libjuju's side as to why the server should hang up like that. The local charm path handling seems to be right, the ssl context is there in the `HTTPSConnection` object, and the url handling for the model seems to be right too. Not to mention that our own [integration test about upgrading local charm](https://github.com/juju/python-libjuju/blob/faa017b8c6c1d80640e6c02d4e457baac76d0357/tests/integration/test_application.py#L193) is always passing.

So I'm not entirely sure what's going on, @sed-i, it might be useful if you can provide an isolated example to reproduce this issue.

If this is happening in your test suite, then it might be possible that the server side is limiting the amount of requests to be made in a certain time period. I believe that would also explain why the cli is working fine. Any thoughts @SimonRichardson ?

**Comment by sed-i** [comment]
A have a déjà vu about `series`. Any chance the following is not working with sidecar charms?

https://github.com/juju/python-libjuju/blob/faa017b8c6c1d80640e6c02d4e457baac76d0357/juju/model.py#L824-L825

**Comment by cderici** [comment]
Good catch, @sed-i! Looks like it's indeed failing with the sidecar charms, I was able to replicate the problem. 

Working on a fix for it :+1:
