### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by mullumaus** [juju/python-libjuju#621]
Function "_print_status_apps" in file juju/status.py, below piece of code should check if app.workload_version or app.charm_channel is None. 

https://github.com/juju/python-libjuju/blob/cbeae7063f8a19dc1e1ed3638f8025735f6d9bc0/juju/status.py#L117

If a charm is deployed from local rather than from charmstore, workload_version and app.charm_channel may be None

Traceback (most recent call last):
  File "./lib/test_lib_juju.py", line 26, in <module>
    main()
  File "./lib/test_lib_juju.py", line 7, in main
    juju_status = juju_get_status("bcache", keep_relations_info=True, jsfy=False, format_status=True)
  File "~lib/lib_juju.py", line 57, in juju_get_status
    juju_status = loop.run(get_juju_status(model_name, keep_relations_info, jsfy, format_status))
  File "~venv/lib/python3.8/site-packages/juju/jasyncio.py", line 118, in run
    raise task.exception()
  File "~lib/lib_juju.py", line 108, in get_juju_status
    juju_status = await formatted_status(model)
  File "~venv/lib/python3.8/site-packages/juju/status.py", line 61, in formatted_status
    result_str += _print_status_apps(result_status)
  File "~venv/lib/python3.8/site-packages/juju/status.py", line 116, in _print_status_apps
    result_str += limits.format(
TypeError: unsupported format string passed to NoneType.__format__
Task was destroyed but it is pending!

**Comment by juanmanuel-tirado** [comment]
Changes from #622 should fix this. Please reopen if needed.
