### ISSUE TITLE
Can't deploy charms with juju 2.8.11

### ISSUE THREAD

**Issue by facundofc** [juju/python-libjuju#623]
Deploying charms seems to be broken if using juju version 2.8.11. This is my setup:

```console
$ pip3 show juju | grep -i version
Version: 2.9.6
$ juju version
2.8.11-bionic-amd64
$ juju controllers --format json | jq -r '.controllers["localhost-localhost"]["agent-version"]'
2.8.11
```

And this is the minimal test I was able to come up with:

```python
import sys
import asyncio
import juju.controller

async def controller():
    c = juju.controller.Controller()
    await c.connect_current()
    return c

async def model(controller):
    return await controller.add_model('test')

async def deploy_app(model):
    await model.deploy('ubuntu')

loop = asyncio.get_event_loop()

c = loop.run_until_complete(controller())
m = loop.run_until_complete(model(c))
loop.run_until_complete(m.deploy(sys.argv[1], channel='stable'))

loop.run_until_complete(m.disconnect())
loop.run_until_complete(c.destroy_model('test'))
loop.run_until_complete(c.disconnect())
```

Then this happens, which I believe is expected since juju 2.8 can't deploy charmhub charms:

```console
$ python3 test.py ch:ubuntu       
Traceback (most recent call last):                                                                                                             
  File "test.py", line 18, in <module>
    loop.run_until_complete(m.deploy(sys.argv[1], channel='stable'))                       
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/faq/lp1943748/charm-hw-health/.build/hw-health/.tox/func/lib/python3.6/site-packages/juju/model.py", line 1614, in deploy
    res = await self.deploy_types[str(url.schema)].resolve(url, architecture, application_name, channel, series, entity_url)
  File "/home/faq/lp1943748/charm-hw-health/.build/hw-health/.tox/func/lib/python3.6/site-packages/juju/model.py", line 551, in resolve
    charm_url_str, origin, supported_series = await self.charm_resolver(url, origin)
  File "/home/faq/lp1943748/charm-hw-health/.build/hw-health/.tox/func/lib/python3.6/site-packages/juju/model.py", line 1714, in _resolve_charm
    raise JujuError("resolve charm")                                
juju.errors.JujuError: resolve charm                                               
```

The same thing happens if no prefix is specified (ie, plain `ubuntu`). I don't know if this is expected or not. I would expect it to try charmhub and fallback to the charmstore if that doesn't work, but I'm not sure.

But then this also happens:

```console
$ python3 test.py cs:ubuntu
Traceback (most recent call last):       
  File "test.py", line 18, in <module>                                             
    loop.run_until_complete(m.deploy(sys.argv[1], channel='stable'))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()                       
  File "/home/faq/lp1943748/charm-hw-health/.build/hw-health/.tox/func/lib/python3.6/site-packages/juju/model.py", line 1644, in deploy       
    charm_origin = add_charm_res.charm_origin
AttributeError: 'dict' object has no attribute 'charm_origin'                                                                                  
```

which I don't think it's expected.

**Comment by cderici** [comment]
This looks like a regression in some code path that's being used to resolve charm origins. We do test against older python versions but I don't believe we test against older juju versions for regressions, so I'm not surprised about this issue.

I will try to recreate this with juju `2.8.11` and fix it :+1: Thanks for the report!
