### ISSUE TITLE
Controller.list_models() requires superuser permission

### ISSUE THREAD

**Issue by mullumaus** [juju/python-libjuju#624]
Tried to use python-libjuju to list the models in a controller, I was getting Traceback 'juju.errors.JujuAPIError: permission denied', but I can list models using CLI 'juju models' on the same machine.  

The user has controller "login" access.  python-libjuju can list models successfully after I grant it 'superuser' access to controller. It doesn't make sense that user needs 'superuser' privilege to list model.

libjuju doesn't implement Juju.register() function so I used command 'juju register' register user:
https://pythonlibjuju.readthedocs.io/en/latest/_modules/juju/juju.html#Juju.register

Traceback (most recent call last):
  File "/usr/local/bin/auto_sanitized_juju.py", line 22, in <module>
    main()
  File "/usr/local/bin/auto_sanitized_juju.py", line 17, in main
    for model in juju_get_models():
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/lib/lib_juju.py", line 24, in juju_get_models
    models = loop.run(get_juju_models())
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/jasyncio.py", line 118, in run
    raise task.exception()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/lib/lib_juju.py", line 130, in get_juju_models
    async with JujuController() as controller:
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/lib/lib_juju.py", line 89, in __aenter__
    await self._controller.connect()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/controller.py", line 136, in connect
    await self.update_endpoints()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/controller.py", line 139, in update_endpoints
    info = await self.info()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/controller.py", line 280, in info
    uuids = await self.model_uuids()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/controller.py", line 550, in model_uuids
    response = await controller_facade.AllModels()
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/client/facade.py", line 482, in wrapper
    reply = await f(*args, **kwargs)
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/client/_client9.py", line 2044, in AllModels
    reply = await self.rpc(msg)
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/client/facade.py", line 655, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/client/connection.py", line 626, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: permission denied
Task was destroyed but it is pending!
task: <Task pending coro=<Connection._pinger() running at /var/lib/juju/agents/unit-juju-lint-4/charm/venv/juju/client/connection.py:571> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f823cd76f78>()]>>
Task was destroyed but it is pending!

~$ juju models
Controller: localhost-localhost

Model             Cloud/Region         Type  Status     Machines  Units  Access  Last connection
admin/bcache      localhost/localhost  lxd   available         3      4  read    7 minutes ago
admin/controller  localhost/localhost  lxd   available         1      -  read    just now

$ juju grant jujukeeper login -c localhost-localhost
ERROR could not grant controller access: user already has "login" access or greater
$ juju grant jujukeeper superuser  -c localhost-localhost

**Comment by jameinel** [comment]
So I believe Juju has 2 methods to list models. One to list the models that your user can see, and one to list all of the models that a controller is running. It looks like this one is doing the Everything On the Controller, and we should change that to be 'everything for this user'.
I believe this is `Controller.AllModels` vs `ModelManager.ListModels`

**Comment by cderici** [comment]
> I believe this is `Controller.AllModels` vs `ModelManager.ListModels`

This is correct. At libjuju's side `model_uuids` method that's being used to list the models in the Controller is using the Controller facade to make the call to `AllModels`. Instead, it should be using the `ModelManager`, because `juju models` uses the `ModelManager.ListModelSummaries` method.
