### ISSUE TITLE
not able to deploy ubuntu charm with 2.9.3

### ISSUE THREAD

**Issue by patriciadomin** [juju/python-libjuju#643]
after the transition from charm Store to CharmHub we are not able to deploy ubuntu charm: 
```
Traceback (most recent call last):
  File "/srv/scalebot/repo/tests/juju-deploy-ubuntu.py", line 29, in main
    constraints=constraints.parse(argsconstraints),
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1470, in deploy
    entity=entity)
  File "/usr/local/lib/python3.6/dist-packages/juju/model.py", line 1531, in _add_store_resources
    } for resource in entity['Meta']['resources']
KeyError: 'resources'
```
Code: 
```
     application = await model.deploy(
            "ubuntu",
            application_name="ubuntu",
            series=argsseries,
            channel="stable",
            constraints=constraints.parse(argsconstraints),
        )
```
Juju version: 2.9.22 
Python library for Juju: 2.9.3

**Comment by patriciadomin** [comment]
upgrading py-libjuju to latest one: 
```
$ pip3 show juju
Name: juju
Version: 2.9.7
``` has fixed and we now can deploy ubuntu charm
