### ISSUE TITLE
Every integration test ends with `RuntimeError: Event loop is closed`

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#657]
While integration tests pass and all is ok, in the logs I always see this at the end:

```
Exception ignored in: <coroutine object Connection._pinger.<locals>._do_ping at 0x7faed2a6d1c0>
Traceback (most recent call last):
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py", line 559, in _do_ping
    await pinger_facade.Ping()
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/facade.py", line 482, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/_client1.py", line 13627, in Ping
    reply = await self.rpc(msg)
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/facade.py", line 655, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py", line 619, in rpc
    result = await self._recv(msg['request-id'])
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py", line 436, in _recv
    return await self.messages.get(request_id)
  File "/home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/utils.py", line 103, in get
    value = await self._queues[id].get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 168, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-1556' coro=<Connection._pinger.<locals>._do_ping() done, defined at /home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py:557> wait_for=<Future cancelled> cb=[create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=<Logger juju....ion (WARNING)>)() at /home/ubuntu/tmp/loki-k8s-operator/.tox/integration/lib/python3.9/site-packages/juju/jasyncio.py:64]>
```

**Comment by cderici** [comment]
Yeah I noticed this as well, thought we cleaned this all up in #580, thanks for bringing it up,  I'll take a closer look soon :+1:

**Comment by sed-i** [comment]
#658 was reverted in #672.
Reopen this please?
