### ISSUE TITLE
Error deploying sidecar and podspec charms using ops_test

### ISSUE THREAD

**Issue by natalian98** [juju/python-libjuju#684]
When deploying both sidecar and podspec charms in a test using `ops_test.model.deploy`, we get an error:
```
Traceback (most recent call last):
  File "/home/ubuntu/code/dex-auth/tests/integration/test_charm.py", line 73, in test_relations
    await ops_test.model.deploy(istio_pilot, channel="latest/edge", trust=True)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1644, in deploy
    resources = await self._add_charmhub_resources(res.app_name,
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1762, in _add_charmhub_resources
    res = await charm_facade.CharmInfo(entity_url)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 501, in wrapper
    result = cls.from_json(reply['response'])
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 4800, in __init__
    meta_ = CharmMeta.from_json(meta) if meta else None
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 672, in from_json
    return cls(**d)
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/_definitions.py", line 5312, in __init__
    assumes_expr_ = ExpressionTree.from_json(assumes_expr) if assumes_expr else None
  File "/home/ubuntu/code/dex-auth/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 668, in from_json
    for k, v in (data or {}).items():
AttributeError: 'list' object has no attribute 'items'
```
The podspec charm uses `min-juju-version` and `series: [kubernetes]` while sidecar uses `assumes: juju >= 2.9.0`. We suspect that they are somehow interfering each other and causing that error. The charms can be deployed in the same model using CLI.

This issue was consulted with @cderici and it looks like it's about how the `assumes` field in the charm's metadata is communicated through the API.

**Comment by juanmanuel-tirado** [comment]
Hi @natalian98 could you please attach a reproducible code fragment for testing?

**Comment by juanmanuel-tirado** [comment]
Just an upgrade on this issue. The `assume: 'juju >= 2.9.0'` breaks the conversions to a dict inside the `facade.py`. This requires further investigation because this function is expecting key-value pairs, not something like `k >= v`

**Comment by juanmanuel-tirado** [comment]
@natalian98 Could you please try with #685 ?
