### ISSUE TITLE
Handle websocket connection resets

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/python-libjuju#7]
Running against a shared controller in aws, I'm observing the websocket connections being forcefully reset by the server end. It appears to happen consistently when waiting for a machine to be provisioned, which can take a while. Not sure if this is a bug in Juju or expected behavior, but either way we should probably add some auto-reconnect stuff to the client.

**Comment by petevg** [comment]
This just bit me, with hadoop-processing in matrix, with a local controller, against local lxd containers. +1 on dropping a workaround in.

**Comment by petevg** [comment]
I poked at this. For the common case, this is pretty simple to fix. The following tweak to the `rpc` routine in facade.py needs cleaning up, but it works:

```
    async def rpc(self, msg):
        try:
            result = await self.connection.rpc(msg, encoder=TypeEncoder)
        except Exception as e:
            await self.connection.connect_current()
            result = await self.connection.rpc(msg, encoder=TypeEncoder)    
        return result
```

Unfortunately, that doesn't address the case where you've done something more complex with your connection than connecting to the current model. @tvansteenburgh did you have any thoughts on how to handle the reconnect more generically? We could save off the args that a user passes into the initial call to `connect`, but that includes the model's password, and I'd rather not have that bouncing around memory if we don't need to ...

**Comment by johnsca** [comment]
Since the last couple of PRs, I can't deploy any bundle due to getting the not connected error 100% of the time on the first `addUnit` call after the charms are added.  There doesn't seem to be any sort of delay or timeout involved, it's just immediately failing.  Perhaps reopening the websocket will be sufficient, but I'm concerned that we've started doing something that is causing the connection to be closed.

**Comment by johnsca** [comment]
It looks like we're crashing the controller.  O_O

```
2016-11-30 00:02:28 ERROR juju.state allwatcher.go:357 getting a public address for unit "elasticsearch/0" failed: "unit elasticsearch/0 cannot get assigned machine: unit \"elasticsearch/0\" is not assigned to a machine"
2016-11-30 00:02:28 ERROR juju.state allwatcher.go:361 getting a private address for unit "elasticsearch/0" failed: "unit elasticsearch/0 cannot get assigned machine: unit \"elasticsearch/0\" is not assigned to a machine"
2016-11-30 00:02:28 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
2016-11-30 00:02:30 ERROR juju.state database.go:231 using unknown collection "remoteApplications"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x75e709]

goroutine 5315 [running]:
panic(0x2ac1e60, 0xc82000e080)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/juju/juju/state.(*State).parsePlacement(0xc820629ea0, 0x0, 0x0, 0x0, 0x0)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/state/state.go:1354 +0x39
github.com/juju/juju/state.(*State).addMachineWithPlacement(0xc820629ea0, 0xc820c36ee0, 0x0, 0xc82050d600, 0x0, 0x0)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/state/state.go:1377 +0xb4
github.com/juju/juju/state.(*State).AssignUnitWithPlacement(0xc820629ea0, 0xc820c36ee0, 0x0, 0x0, 0x0)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/state/state.go:1317 +0x45
github.com/juju/juju/apiserver/application.stateShim.AssignUnitWithPlacement(0xc820629ea0, 0xc820c36ee0, 0x0, 0x0, 0x0)
	<autogenerated>:504 +0x57
github.com/juju/juju/juju.AddUnits(0x7f7e6f7a8ba0, 0xc820629ea0, 0x7f7e6f7a8bd0, 0xc820710fc0, 0xc820bd4fea, 0x6, 0x1, 0xc82149af80, 0x1, 0x4, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/juju/deploy.go:139 +0x542
github.com/juju/juju/apiserver/application.addApplicationUnits(0x7f7e6f85f018, 0xc820629ea0, 0xc820bd4fea, 0x6, 0x1, 0xc82149af80, 0x1, 0x4, 0x0, 0x0, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/apiserver/application/application.go:609 +0x253
github.com/juju/juju/apiserver/application.(*API).AddUnits(0xc820fd2280, 0xc820bd4fea, 0x6, 0x1, 0xc82149af80, 0x1, 0x4, 0x0, 0x0, 0x0, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/apiserver/application/application.go:620 +0x1d2
reflect.Value.call(0x2f1f9a0, 0xc820fd2280, 0x613, 0x30de4f8, 0x4, 0xc82149b000, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x2f1f9a0, 0xc820fd2280, 0x613, 0xc82149b000, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
github.com/juju/juju/rpc/rpcreflect.newMethod.func6(0x2f1f9a0, 0xc820fd2280, 0x16, 0x2ba5940, 0xc8210961b0, 0x199, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/rpc/rpcreflect/type.go:323 +0x14b
github.com/juju/juju/apiserver.(*srvCaller).Call(0xc820c08300, 0x0, 0x0, 0x2ba5940, 0xc8210961b0, 0x199, 0x0, 0x0, 0x0, 0x0, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/apiserver/root.go:137 +0x120
github.com/juju/juju/rpc.(*Conn).runRequest(0xc82063c990, 0x7f7e6f8a4ea0, 0xc820c08300, 0x3a076c0, 0x15, 0xc820bd4f40, 0xb, 0x3, 0x0, 0x0, ...)
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/rpc/server.go:490 +0xd9
created by github.com/juju/juju/rpc.(*Conn).handleRequest
	/build/juju-core-UV0fcM/juju-core-2.0.2/src/github.com/juju/juju/rpc/server.go:420 +0x6cd
2016-11-30 00:02:31 INFO juju.cmd supercommand.go:63 running jujud [2.0.2.1 gc go1.6.2]
2016-11-30 00:02:31 DEBUG juju.cmd supercommand.go:64   args: []string{"/var/lib/juju/tools/machine-0/jujud", "machine", "--data-dir", "/var/lib/juju", "--machine-id", "0", "--debug"}
2016-11-30 00:02:31 DEBUG juju.agent agent.go:509 read agent config, format "2.0"
2016-11-30 00:02:31 INFO juju.cmd.jujud machine.go:404 machine agent machine-0 start (2.0.2.1 [gc])
2016-11-30 00:02:31 DEBUG juju.wrench wrench.go:112 couldn't read wrench directory: stat /var/lib/juju/wrench: no such file or directory
2016-11-30 00:02:31 INFO juju.worker.upgradesteps worker.go:72 no upgrade steps required or upgrade steps for 2.0.2.1 have already been run.
2016-11-30 00:02:31 INFO juju.worker runner.go:256 start "engine"
```

**Comment by tvansteenburgh** [comment]
@petevg If there's a password, it's already in memory anyway. If you get disconnected I think you'll want to (in the Connection class):

    await self.open()
    await self.login(self.username, self.password, self.macaroons)

and then retry the rpc call.

**Comment by petevg** [comment]
@tvansteenburgh @johnsca It looks like the resets that I and (@johnsca) were running into were actually null pointer exceptions in juju core.

I'm currently thinking that the best way to handle this is to fix the exceptions by not passing things in to the api that will cause them. I've backed off on writing a generic retrying into `.rpc` for now.

Also, we should probably file the exceptions with juju core. You shouldn't be able to crash core with an api call :-)

**Comment by petevg** [comment]
@arosales @tvansteenburgh This issue can probably be closed. I don't think that it's a good idea to hide a retry loop inside of the api, for the reasons mentioned above (it might leave an application in an unknown state). And I think that we're pretty good about passing up reasonable exceptions when things break.
