### ISSUE TITLE
"Already exists" exception raised when programmatically deploying charms

### ISSUE THREAD

**Issue by arturo-seijas** [juju/python-libjuju#712]
I've recently come across an intermittent error when trying to programmatically deploy some charms on microk8s. The issue has first appeared when migrating to libjuju 3.0.1.

Due to the exception not being raised in most executions I suspect it could be caused by the concurrent deployments.

The failing snippet is the following.
```
await asyncio.gather(
    ops_test.model.deploy("postgresql-k8s"),
    ops_test.model.deploy("redis-k8s", "redis-broker"),
    ops_test.model.deploy("redis-k8s", "redis-cache"),
)
```
```
Traceback (most recent call last):
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 293, in _asyncgen_fixture_wrapper
    result = event_loop.run_until_complete(setup())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 275, in setup
    res = await gen_obj.__anext__()
  File "/home/runner/work/indico-operator/indico-operator/tests/integration/conftest.py", line 33, in app
    await asyncio.gather(
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1745, in deploy
    add_charm_res = await self._add_charm(identifier, res.origin)
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1817, in _add_charm
    return await charms_facade.AddCharm(charm_origin=origin, url=charm_url, force=False)
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 481, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/client/old_clients/_client4.py", line 2241, in AddCharm
    reply = await self.rpc(msg)
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 654, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/runner/work/indico-operator/indico-operator/.tox/integration/lib/python3.8/site-packages/juju/client/connection.py", line 634, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: already exists
```

More info:
Juju version: 2.9.33
Python version: 3.8
Microk8s version:1.24.3

Thank you

**Comment by juanmanuel-tirado** [comment]
Could you please run the same statements out of an `asyncio.gather` to confirm potential disruptions due to the `asyncio` versioning. I've been trying to reproduce this with Python 3.10 with no success.

**Comment by cderici** [comment]
Yeah this works for me as well, tried it with the versions given and multiple python versions (including `3.8`), maybe the script running the deploy accidentally ran twice in a row?

Marking this as invalid until reproducible steps are provided.

**Comment by arturo-seijas** [comment]
I just got again the same error. It is not very frequent, but it certainly looks like a concurrency issue. There's only one script running at a time and the execution is quite isolated. I provide the link to one of the failing executions: https://github.com/canonical/indico-operator/runs/7990791668?check_suite_focus=true

**Comment by arturo-seijas** [comment]
Hi! I'm closing this ticket. We haven't experienced this with the new versions
