### ISSUE TITLE
[Bug]: None of the example codes actually correctly shut down

### ISSUE THREAD

**Issue by tbaumann** [juju/python-libjuju#743]
### Description

Asynchronous python is already hard enough. But with none of the examples actually working correctly it's really hard to understand best practices.

For example
```
(python-libjuju) tilli@zuse:~/git/python-libjuju/examples$ python fullstatus.py 
Applications: ['ubuntu']
Machines: ['2']
Relations: []
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f817596b6d0>
transport: <_SelectorSocketTransport closing fd=7>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 915, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 921, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 716, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 728, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending name='Task-31' coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py:936> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>
Task was destroyed but it is pending!
task: <Task pending name='Task-32' coro=<WebSocketCommonProtocol.keepalive_ping() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py:1218> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f8175917610>
Traceback (most recent call last):
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1329, in close_connection
    await self.close_transport()
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1347, in close_transport
    if await self.wait_for_connection_lost():
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1372, in wait_for_connection_lost
    await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 405, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop
Task was destroyed but it is pending!
task: <Task pending name='Task-33' coro=<WebSocketCommonProtocol.close_connection() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py:1273> wait_for=<Task pending name='Task-31' coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py:936> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-34' coro=<Connection._receiver() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/connection.py:528> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-39' coro=<Connection._pinger() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/connection.py:556> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-44' coro=<WebSocketCommonProtocol.recv() done, defined at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/websockets/legacy/protocol.py:486> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=<Logger juju....ion (WARNING)>)() at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/jasyncio.py:64]>
Task was destroyed but it is pending!
task: <Task pending name='Task-45' coro=<Event.wait() done, defined at /usr/lib/python3.10/asyncio/locks.py:201> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

### Urgency

Casually reporting

### Python-libjuju version

3.0.2

### Juju version

2.9.35

### Reproduce / Test

```python
Run basically any of the examples. I haven't found one that actually shuts down correctly.
```

**Comment by tbaumann** [comment]
If I use `asyncio.run()` instead of `jasyncio.run()` everything works normal. :astonished:

**Comment by juanmanuel-tirado** [comment]
Some clarifications and a bit of blah blah.

A bit of history. Python-libjuju was designed to support several Python versions. The `async` module had changes in the past that broke backwards compatibility. `jasyncio` was added to provide a binding to abstract away these kind of issues and ensure compatibility across versions.

Current situation. We are aware of this bug and we are evaluating the most convenient way to proceed. The final solution may end up with the complete removal of the `async` module from python-libjuju. This is TBD.

Said this. I understand your frustration, and I thank you for communicating this bug. The examples folder will be changed accordingly once we have a final decision on how to proceed. Unfortunately, this issue will persist meanwhile.

**Comment by tbaumann** [comment]
ok thanks
