### ISSUE TITLE
[Bug]: `deploy` fails attempting to infer series in a k8s charm deployed from path

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#765]
### Description

On a k8s charm (grafana-k8s), I get the following error in an itest:
```
Traceback (most recent call last):
  File "/home/ubuntu/code/grafana-k8s-operator/tests/integration/test_external_url.py", line 27, in test_deploy
    await asyncio.gather(
  File "/home/ubuntu/code/grafana-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 1820, in deploy
    raise JujuError(
juju.errors.JujuError: Couldn't determine series for charm at /home/ubuntu/code/grafana-k8s-operator/.tox/integration/tmp/pytest/test-external-url-4opr0/charms/grafana-k8s_ubuntu-20.04-amd64.charm. Pass a 'series' kwarg to Model.deploy().
```

Passing `force=True` doesn't help.

Passing `series="kubernetes"` results in a hangup:
```
controller-0: 12:44:59.563 INFO juju.worker.caasapplicationprovisioner.runner stopped "grafana", err: getting image for base: channel "kubernetes/" not valid
controller-0: 12:44:59.563 ERROR juju.worker.caasapplicationprovisioner.runner exited "grafana": getting image for base: channel "kubernetes/" not valid
```

Passing `series="focal"` works.

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.0.4

### Juju version

2.9.36

### Reproduce / Test

```python
https://github.com/canonical/grafana-k8s-operator/blob/catch-ingress-ready/tests/integration/test_external_url.py
```

**Comment by juanmanuel-tirado** [comment]
You're right. The logic to determine the series to be used in local charms have not been exposed correctly for 2.9 controllers. We will work to fix it. Thanks for reporting.
