### ISSUE TITLE
[Bug]: Support for 2.9.37 seems broken

### ISSUE THREAD

**Issue by tbaumann** [juju/python-libjuju#778]
### Description

I get this error trying to connect to latest juju agent version 2.9.37
```
handle: <Handle create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=None)(<Task finishe...nt.ClientV5')>) at /home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/jasyncio.py:64>
Traceback (most recent call last):
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/jasyncio.py", line 66, in _task_result_exp_handler
    task.result()
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/facade.py", line 481, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/old_clients/_client2.py", line 1091, in Next
    reply = await self.rpc(msg)
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/overrides.py", line 106, in rpc
    result = await client.WatchAll()
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/facade.py", line 481, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/_client5.py", line 548, in WatchAll
    reply = await self.rpc(msg)
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/facade.py", line 654, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/tilli/.virtualenvs/python-libjuju/lib/python3.10/site-packages/juju/client/connection.py", line 634, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: internal error, Client(5) claimed to return *client.Client but returned *client.ClientV5

During handling of the above exception, another exception occurred:
```

When I deploy a model with 2.9.33 I can use it fine.

### Urgency

Casually reporting

### Python-libjuju version

master (88eb6c4b85d7d960fdc65b89ac0d5e79ee4cc6bc)

### Juju version

2.9.37

### Reproduce / Test

```python
`python examples/fullstatus.py`
```

**Comment by cderici** [comment]
Thanks for reporting this, but it's not broken, we're transitioning fully into the 3.0 in the coming releases of pylibjuju, so dropping support for 2.9 track on the master branch (see #774 for details).

For people who want to continue using the Juju 2.9.x (with libjuju <=3.0.1), we intend to occasionally cherry pick patches and fixes onto the 2.9 branch on libjuju to keep things relatively up-to-date there, however, there's not gonna be an active development on the 2.9 track anymore (neither on juju nor libjuju).

**Comment by tbaumann** [comment]
Not exactly a great move to drop backwards compatibility. 2.9 is far from being dead already. Especially since migrating to 3.0 is maximally painful.

First of all it is compatible with 2.9.33 but not 2.9.37. So old versions will randomly work or not?
And the error message in that case should really hint at the solution.

**Comment by cderici** [comment]
> Not exactly a great move to drop backwards compatibility. 2.9 is far from being dead already. Especially since migrating to 3.0 is maximally painful.

Well that's the point of major versions bumps. Pylibjuju 3.0.x never had any obligations as to supporting Juju 2.9.x, we just wanted to keep the support for 2.9 while introducing support for 3.0 so people have some time to adjust and have a smooth transition, instead of a sharp drop at the Pylibjuju 3.0. We also [announced](https://github.com/juju/python-libjuju/releases/tag/3.0.0) that we're switching to semantic versioning, therefore, ultimately, if you want to use the Juju 3.x.y, then you need to be using Pylibjuju 3.x.y, and vice versa.

> First of all it is compatible with 2.9.33 but not 2.9.37. So old versions will randomly work or not? And the error message in that case should really hint at the solution.

I'm surprised that the current master branch runs the Juju 2.9.33. That would be a bug, and that means something may have gone wrong in #774, I need to take a closer look to confirm, @juanmanuel-tirado is out on leave, maybe he can confirm if I can't until he's back.

**Comment by juanmanuel-tirado** [comment]
I just checked #777 with a 2.9.37 controller and I get a `JujuConnectionError: juju server-version 2.9.37 not supported`.

**Comment by tbaumann** [comment]
Perhaps something went wrong with my virtualenv.
I just did `python setup.py install` in the master branch to be sure.
I just got this really weird backtrace above.

I can have a look tomorrow as well.

**Comment by tbaumann** [comment]
The installed version identifies as 
`juju               3.0.2` via `pip list`

Works with a 2.9.33 controller with no complaints

**Comment by tbaumann** [comment]
I think I was just using the setup tools wrong.I used all pip and made sure to remove all old library traces. And it behaves as you would expect now. Including a sensible error message for unsupported versions.

Sorry for the mess. All good.

**Comment by cderici** [comment]
Glad it worked out well @tbaumann, yeah the #774 is not in any release yet, so the current pip versions should work fine.

Thanks again for reporting, and feel free to report any discrepancies you observe in the future as well :+1:
