### ISSUE TITLE
[Bug]: Namespace length error when running tests

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#818]
### Description

If you try to run a single itest,
```bash
tox -e integration -- -k test_deploy_bundle_with_multiple_overlays_with_include_files
```
The autogenerated namespace "test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9" is too long and we get a JujuAPIError. Should the name be auto truncated?

```
______________ test_deploy_bundle_with_multiple_overlays_with_include_files ______________
[gw1] linux -- Python 3.10.6 /home/ubuntu/code/python-libjuju/.tox/py3/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/code/python-libjuju/tests/integration/test_model.py", line 264, in test_deploy_bundle_with_multiple_overlays_with_include_files
    async with base.CleanModel() as model:
  File "/home/ubuntu/code/python-libjuju/tests/base.py", line 98, in __aenter__
    self._model = await self._controller.add_model(model_name)
  File "/home/ubuntu/code/python-libjuju/juju/controller.py", line 342, in add_model
    model_info = await model_facade.CreateModel(
  File "/home/ubuntu/code/python-libjuju/juju/client/facade.py", line 483, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/ubuntu/code/python-libjuju/juju/client/_client9.py", line 624, in CreateModel
    reply = await self.rpc(msg)
  File "/home/ubuntu/code/python-libjuju/juju/client/facade.py", line 656, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/ubuntu/code/python-libjuju/juju/client/connection.py", line 641, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: creating namespace "test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9": Namespace "test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9" is invalid: [metadata.name: Invalid value: "test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9": must be no more than 63 characters, metadata.labels: Invalid value: "test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9": must be no more than 63 characters]
```

### Urgency

Casually reporting

### Python-libjuju version

3.0.4

### Juju version

3.0.3 (22197)

### Reproduce / Test

```python
tox -e integration -- -k test_deploy_bundle_with_multiple_overlays_with_include_files
```

**Comment by juanmanuel-tirado** [comment]
The simplest solution here is to have a shorter test name. Nevertheless, integration tests for python-libjuju run on lxd, no k8s. And this error applies to the namespace limitations in k8s. If you create a model with the same name for lxd, that will work:
```bash
juju_29 list-models
Controller: test2942

Model                                                                         Cloud/Region         Type  Status     Machines  Access  Last connection
controller                                                                    localhost/localhost  lxd   available         1  admin   just now
default                                                                       localhost/localhost  lxd   available         0  admin   26 seconds ago
test-ddac-test-deploy-bundle-with-multiple-overlays-with-include-files-72e9*  localhost/localhost  lxd   available         0  admin   just now
```
