### ISSUE TITLE
asyncio  & libjuju 

### ISSUE THREAD

**Issue by sfeole** [juju/python-libjuju#83]
I've been seeing this exception occurring in many of my libjuju scripts I have, Just to make sure it was not an issue with my code, I checked the libjuju/examples/*.py files and also see this error while running most of the example scripts.

I've been looking through asyncio bugs and have somewhat a good understanding of why this is happening. So I'm wondering if any other folks here have been hitting this error below?   

<.SNIP.>

DEBUG:juju.model:Stopping watcher task
DEBUG:juju.model:Closing watcher connection
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=8, data=b'\x03\xe8')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":5,"error":"watcher was stopped","response":{}}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=8, data=b'\x03\xe8')
DEBUG:juju.model:Closing model connection
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=8, data=b'\x03\xe8')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=8, data=b'\x03\xe8')
DEBUG:juju.controller:Closing controller connection
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=8, data=b'\x03\xe8')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=8, data=b'\x03\xe8')
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

**Comment by petevg** [comment]
@sfeole I've seen that, too (on Xenial, running python 3.5, for the record). I believe that there's an issue with the way that we clean up our loop in the juju/loop.py helper (or an issue with the way that we pass the keyboard interrupting signal handler into the helper in the first place).
