### ISSUE TITLE
Feature request: `Unit.ssh` does not work with k8s charms

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#835]
### Description

Currently, [`Unit.ssh`](https://github.com/juju/python-libjuju/blob/d809caf11dc2e16fd2dc2821383a8a452c634a9e/juju/unit.py#L311) only works for machine units.

```
>>> await model.units['grafana/0'].ssh("curl -s --user admin:eoIaI2uThcVh localhost:3000/api/search")
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/__main__.py", line 58, in runcode
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/juju/unit.py", line 321, in ssh
    return await self.machine.ssh(command, user, proxy, ssh_opts)
AttributeError: 'NoneType' object has no attribute 'ssh'
```

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.0.4

### Juju version

2.9.42

### Reproduce / Test

```python
$ python3 -m asyncio

>>> from juju.model import Model
>>> model = Model()
>>> await model.connect_current()
>>> await model.units['grafana/0'].ssh("curl -s --user admin:eoIaI2uThcVh localhost:3000/api/search")
```

**Comment by juanmanuel-tirado** [comment]
This is not a bug. This is a missing feature. There is no code in python-libjuju supporting ssh connectivity to k8s charms. I changed the label.
