### ISSUE TITLE
Error: no credentials provided

### ISSUE THREAD

**Issue by mhmoerma** [juju/python-libjuju#84]
When running one of the provided examples (for instance, the one given in the Quickstart in the docs), I get a `no credentials provided` JuJuAPIError. But there are valid macaroons given in the login function.
Running Python 3.5.2 on Ubuntu 16.4, with the latest version of python-libjuju installed.
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:websocket:Driver connected to juju wss://xxx.xxx.xxx.xxx:17070/model/85d19189-e553-4885-8939-81a49a582420/api
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<run() done, defined at test.py:9> exception=JujuAPIError('no credentials provided',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 15, in run
    await model.connect_current()
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 396, in connect_current
    self.connection = await connection.Connection.connect_current()
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 222, in connect_current
    '{}:{}'.format(controller_name, model_name))
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 274, in connect_model
    endpoint, model_uuid, username, password, cacert, macaroons)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 186, in connect
    await client.login(username, password, macaroons)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 297, in login
    "macaroons": macaroons or []
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 95, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: no credentials provided
```

**Comment by tvansteenburgh** [comment]
It looks like you're using Model.connect_current(), which won't work for macaroon auth right now. Trying connecting as shown in this example: https://pythonhosted.org/juju/narrative/controller.html#connecting-with-macaroon-authentication

**Comment by mhmoerma** [comment]
I switched to connecting with username/password which worked. Thanks!
