### ISSUE TITLE
Error: unkown version (3) of interface "Application"

### ISSUE THREAD

**Issue by mhmoerma** [juju/python-libjuju#85]
When trying to deploy an application to a model, an APIError is thrown: `unknown version (3) of interface "Application"`

```
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/ubuntu-10/meta/any HTTP/1.1" 200 21
DEBUG:juju.model:Deploying cs:ubuntu-10
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<run() done, defined at test.py:7> exception=JujuAPIError('unknown version (3) of interface "Application"',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 33, in run
    channel='stable',
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1045, in deploy
    result = await app_facade.Deploy([app])
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 317, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/_client.py", line 7618, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 436, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 95, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: unknown version (3) of interface "Application"
```

**Comment by tvansteenburgh** [comment]
Can you add this to your script:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

Then re-run and paste full debug output here. Thanks!

**Comment by mhmoerma** [comment]
```
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/ubuntu-10/meta/any HTTP/1.1" 200 21
DEBUG:juju.model:Deploying cs:ubuntu-10
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Client",\n  "request": "AddCharm",\n  "params": {\n    "url": "cs:ubuntu-10",\n    "channel": "stable"\n  },\n  "version": 1,\n  "request-id": 4\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Application",\n  "request": "Deploy",\n  "params": {\n    "applications": [\n      {\n        "placement": [],\n        "channel": "stable",\n        "storage": null,\n        "resources": null,\n        "series": "trusty",\n        "charm-url": "cs:ubuntu-10",\n        "config-yaml": null,\n        "application": "ubuntu",\n        "config": null,\n        "constraints": null,\n        "endpoint-bindings": null,\n        "num-units": 1\n      }\n    ]\n  },\n  "version": 3,\n  "request-id": 5\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":5,"error":"unknown version (3) of interface \\"Application\\"","error-code":"not implemented","response":{}}')
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<run() done, defined at test.py:7> exception=JujuAPIError('unknown version (3) of interface "Application"',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 33, in run
    channel='stable',
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1045, in deploy
    result = await app_facade.Deploy([app])
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 317, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/_client.py", line 7618, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 436, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 95, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: unknown version (3) of interface "Application"
```

**Comment by tvansteenburgh** [comment]
This doesn't appear to be the full log. It doesn't show websocket debug output from the initial connection and API login. Did you truncate the log? If not, make sure the `logging.basicConfig(level=logging.DEBUG)` happens at the beginning of your script.

**Comment by mhmoerma** [comment]
I just pasted the part of the application deploy, here is the full log: 
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:websocket:Driver connected to juju wss://34.249.140.16:17070/api
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {},\n  "request": "RedirectInfo",\n  "version": 3,\n  "request-id": 1\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":1,"error":"not redirected","response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {\n    "auth-tag": "user-admin",\n    "macaroons": [],\n    "credentials": "admin",\n    "nonce": "1O\\f\\u000bB@zV\\n&.f"\n  },\n  "request": "Login",\n  "version": 3,\n  "request-id": 2\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":2,"response":{"servers":[[{"value":"34.249.140.16","type":"ipv4","scope":"public","port":17070},{"value":"172.31.20.19","type":"ipv4","scope":"local-cloud","port":17070},{"value":"127.0.0.1","type":"ipv4","scope":"local-machine","port":17070},{"value":"::1","type":"ipv6","scope":"local-machine","port":17070}]],"controller-tag":"controller-b0cb605e-a7aa-4df0-8eff-21ee41d0e1dc","user-info":{"display-name":"","identity":"user-admin","last-connection":"2017-03-13T18:06:56Z","controller-access":"superuser","model-access":""},"facades":[{"name":"AllModelWatcher","versions":[2]},{"name":"Bundle","versions":[1]},{"name":"Cloud","versions":[1]},{"name":"Controller","versions":[3]},{"name":"HighAvailability","versions":[2]},{"name":"MigrationTarget","versions":[1]},{"name":"ModelManager","versions":[2]},{"name":"Pinger","versions":[1]},{"name":"UserManager","versions":[1]}],"server-version":"2.0.0"}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {},\n  "request": "Clouds",\n  "version": 1,\n  "request-id": 3,\n  "type": "Cloud"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":3,"response":{"clouds":{"cloud-aws":{"type":"ec2","auth-types":["access-key"],"regions":[{"name":"ap-northeast-1","endpoint":"https://ec2.ap-northeast-1.amazonaws.com"},{"name":"ap-northeast-2","endpoint":"https://ec2.ap-northeast-2.amazonaws.com"},{"name":"ap-south-1","endpoint":"https://ec2.ap-south-1.amazonaws.com"},{"name":"ap-southeast-1","endpoint":"https://ec2.ap-southeast-1.amazonaws.com"},{"name":"ap-southeast-2","endpoint":"https://ec2.ap-southeast-2.amazonaws.com"},{"name":"eu-central-1","endpoint":"https://ec2.eu-central-1.amazonaws.com"},{"name":"eu-west-1","endpoint":"https://ec2.eu-west-1.amazonaws.com"},{"name":"sa-east-1","endpoint":"https://ec2.sa-east-1.amazonaws.com"},{"name":"us-east-1","endpoint":"https://ec2.us-east-1.amazonaws.com"},{"name":"us-east-2","endpoint":"https://ec2.us-east-2.amazonaws.com"},{"name":"us-west-1","endpoint":"https://ec2.us-west-1.amazonaws.com"},{"name":"us-west-2","endpoint":"https://ec2.us-west-2.amazonaws.com"}]}}}}')
DEBUG:juju.controller:Creating model test
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {\n    "config": null,\n    "name": "test",\n    "credential": null,\n    "cloud-tag": "cloud-aws",\n    "region": null,\n    "owner-tag": "user-admin"\n  },\n  "request": "CreateModel",\n  "version": 2,\n  "request-id": 4,\n  "type": "ModelManager"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"response":{"name":"test","uuid":"9a87a64b-864c-4c53-8116-0582cdf223a4","controller-uuid":"b0cb605e-a7aa-4df0-8eff-21ee41d0e1dc","provider-type":"ec2","default-series":"xenial","cloud-tag":"cloud-aws","cloud-region":"eu-west-1","cloud-credential-tag":"cloudcred-aws_admin_aws-qrama","owner-tag":"user-admin","life":"alive","status":{"status":"available","info":"","since":"2017-03-13T18:07:02.67697639Z"},"users":[{"user":"admin","display-name":"admin","last-connection":null,"access":"admin"}],"machines":null}}')
DEBUG:juju.controller:Exec ('juju', 'add-ssh-key', '-m', 'test', 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCm+ALQUmWROME2sbkWZtNpM/wLz1Qbwliczzg0i8ceF9tA7bYjQHywVqejcCu70/Zrh3rfNXd6nWV7Z34Yckjg1tudTiyOJFI/D/OWLcZ9hnhQrPkBWVREhW2sjDhAN8o1AEVWKvGN8RQceh9JM33xUFgFZ1uzAMTjn3MSM42AqciX5qmhzDkhtxhPWec0OtCu8qDY5xLF5RKeTsYkTkXdMGV335npNm9zMvZTQo5WoGBTPvRqRmOk/p46tF4G6G1JH7sLXUdG1xUE/0wVrZUDxV/CMhVZgATwu2TqTa7R8tdOajMnsWl77ipSZaf+Y/ezqUnA3gL/cvEh0j1rxz89 juju-client-key') -> 0
INFO:websocket:Driver connected to juju wss://34.249.140.16:17070/model/9a87a64b-864c-4c53-8116-0582cdf223a4/api
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {},\n  "request": "RedirectInfo",\n  "version": 3,\n  "request-id": 1\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":1,"error":"not redirected","response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {\n    "auth-tag": "user-admin",\n    "macaroons": [],\n    "credentials": "admin",\n    "nonce": "(2_Lo\\f?6Z&\\"Y"\n  },\n  "request": "Login",\n  "version": 3,\n  "request-id": 2\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":2,"response":{"servers":[[{"value":"34.249.140.16","type":"ipv4","scope":"public","port":17070},{"value":"172.31.20.19","type":"ipv4","scope":"local-cloud","port":17070},{"value":"127.0.0.1","type":"ipv4","scope":"local-machine","port":17070},{"value":"::1","type":"ipv6","scope":"local-machine","port":17070}]],"model-tag":"model-9a87a64b-864c-4c53-8116-0582cdf223a4","controller-tag":"controller-b0cb605e-a7aa-4df0-8eff-21ee41d0e1dc","user-info":{"display-name":"","identity":"user-admin","last-connection":"2017-03-13T18:07:03Z","controller-access":"superuser","model-access":"admin"},"facades":[{"name":"Action","versions":[2]},{"name":"Agent","versions":[2]},{"name":"AgentTools","versions":[1]},{"name":"AllWatcher","versions":[1]},{"name":"Annotations","versions":[2]},{"name":"Application","versions":[1,2]},{"name":"ApplicationScaler","versions":[1]},{"name":"Backups","versions":[1]},{"name":"Block","versions":[2]},{"name":"Bundle","versions":[1]},{"name":"CharmRevisionUpdater","versions":[2]},{"name":"Charms","versions":[2]},{"name":"Cleaner","versions":[2]},{"name":"Client","versions":[1]},{"name":"Deployer","versions":[1]},{"name":"DiscoverSpaces","versions":[2]},{"name":"DiskManager","versions":[2]},{"name":"EntityWatcher","versions":[2]},{"name":"FilesystemAttachmentsWatcher","versions":[2]},{"name":"Firewaller","versions":[3]},{"name":"HighAvailability","versions":[2]},{"name":"HostKeyReporter","versions":[1]},{"name":"ImageManager","versions":[2]},{"name":"ImageMetadata","versions":[2]},{"name":"InstancePoller","versions":[3]},{"name":"KeyManager","versions":[1]},{"name":"KeyUpdater","versions":[1]},{"name":"LeadershipService","versions":[2]},{"name":"LifeFlag","versions":[1]},{"name":"LogForwarding","versions":[1]},{"name":"Logger","versions":[1]},{"name":"MachineActions","versions":[1]},{"name":"MachineManager","versions":[2]},{"name":"MachineUndertaker","versions":[1]},{"name":"Machiner","versions":[1]},{"name":"MeterStatus","versions":[1]},{"name":"MetricsAdder","versions":[2]},{"name":"MetricsDebug","versions":[2]},{"name":"MetricsManager","versions":[1]},{"name":"MigrationFlag","versions":[1]},{"name":"MigrationMaster","versions":[1]},{"name":"MigrationMinion","versions":[1]},{"name":"MigrationStatusWatcher","versions":[1]},{"name":"ModelConfig","versions":[1]},{"name":"NotifyWatcher","versions":[1]},{"name":"Payloads","versions":[1]},{"name":"PayloadsHookContext","versions":[1]},{"name":"Pinger","versions":[1]},{"name":"Provisioner","versions":[3]},{"name":"ProxyUpdater","versions":[1]},{"name":"Reboot","versions":[2]},{"name":"RelationUnitsWatcher","versions":[1]},{"name":"Resources","versions":[1]},{"name":"ResourcesHookContext","versions":[1]},{"name":"Resumer","versions":[2]},{"name":"RetryStrategy","versions":[1]},{"name":"SSHClient","versions":[1]},{"name":"Singular","versions":[1]},{"name":"Spaces","versions":[2]},{"name":"StatusHistory","versions":[2]},{"name":"Storage","versions":[3]},{"name":"StorageProvisioner","versions":[3]},{"name":"StringsWatcher","versions":[1]},{"name":"Subnets","versions":[2]},{"name":"Undertaker","versions":[1]},{"name":"UnitAssigner","versions":[1]},{"name":"Uniter","versions":[4]},{"name":"Upgrader","versions":[1]},{"name":"VolumeAttachmentsWatcher","versions":[2]}],"server-version":"2.0.0"}}')
DEBUG:juju.model:Starting watcher task
INFO:websocket:Driver connected to juju wss://34.249.140.16:17070/model/9a87a64b-864c-4c53-8116-0582cdf223a4/api
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {},\n  "request": "RedirectInfo",\n  "version": 3,\n  "request-id": 1\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":1,"error":"not redirected","response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "Admin",\n  "params": {\n    "auth-tag": "user-admin",\n    "macaroons": [],\n    "credentials": "admin",\n    "nonce": "L>2wWQJ*\'.?l"\n  },\n  "request": "Login",\n  "version": 3,\n  "request-id": 2\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":2,"response":{"servers":[[{"value":"34.249.140.16","type":"ipv4","scope":"public","port":17070},{"value":"172.31.20.19","type":"ipv4","scope":"local-cloud","port":17070},{"value":"127.0.0.1","type":"ipv4","scope":"local-machine","port":17070},{"value":"::1","type":"ipv6","scope":"local-machine","port":17070}]],"model-tag":"model-9a87a64b-864c-4c53-8116-0582cdf223a4","controller-tag":"controller-b0cb605e-a7aa-4df0-8eff-21ee41d0e1dc","user-info":{"display-name":"","identity":"user-admin","last-connection":"2017-03-13T18:07:04Z","controller-access":"superuser","model-access":"admin"},"facades":[{"name":"Action","versions":[2]},{"name":"Agent","versions":[2]},{"name":"AgentTools","versions":[1]},{"name":"AllWatcher","versions":[1]},{"name":"Annotations","versions":[2]},{"name":"Application","versions":[1,2]},{"name":"ApplicationScaler","versions":[1]},{"name":"Backups","versions":[1]},{"name":"Block","versions":[2]},{"name":"Bundle","versions":[1]},{"name":"CharmRevisionUpdater","versions":[2]},{"name":"Charms","versions":[2]},{"name":"Cleaner","versions":[2]},{"name":"Client","versions":[1]},{"name":"Deployer","versions":[1]},{"name":"DiscoverSpaces","versions":[2]},{"name":"DiskManager","versions":[2]},{"name":"EntityWatcher","versions":[2]},{"name":"FilesystemAttachmentsWatcher","versions":[2]},{"name":"Firewaller","versions":[3]},{"name":"HighAvailability","versions":[2]},{"name":"HostKeyReporter","versions":[1]},{"name":"ImageManager","versions":[2]},{"name":"ImageMetadata","versions":[2]},{"name":"InstancePoller","versions":[3]},{"name":"KeyManager","versions":[1]},{"name":"KeyUpdater","versions":[1]},{"name":"LeadershipService","versions":[2]},{"name":"LifeFlag","versions":[1]},{"name":"LogForwarding","versions":[1]},{"name":"Logger","versions":[1]},{"name":"MachineActions","versions":[1]},{"name":"MachineManager","versions":[2]},{"name":"MachineUndertaker","versions":[1]},{"name":"Machiner","versions":[1]},{"name":"MeterStatus","versions":[1]},{"name":"MetricsAdder","versions":[2]},{"name":"MetricsDebug","versions":[2]},{"name":"MetricsManager","versions":[1]},{"name":"MigrationFlag","versions":[1]},{"name":"MigrationMaster","versions":[1]},{"name":"MigrationMinion","versions":[1]},{"name":"MigrationStatusWatcher","versions":[1]},{"name":"ModelConfig","versions":[1]},{"name":"NotifyWatcher","versions":[1]},{"name":"Payloads","versions":[1]},{"name":"PayloadsHookContext","versions":[1]},{"name":"Pinger","versions":[1]},{"name":"Provisioner","versions":[3]},{"name":"ProxyUpdater","versions":[1]},{"name":"Reboot","versions":[2]},{"name":"RelationUnitsWatcher","versions":[1]},{"name":"Resources","versions":[1]},{"name":"ResourcesHookContext","versions":[1]},{"name":"Resumer","versions":[2]},{"name":"RetryStrategy","versions":[1]},{"name":"SSHClient","versions":[1]},{"name":"Singular","versions":[1]},{"name":"Spaces","versions":[2]},{"name":"StatusHistory","versions":[2]},{"name":"Storage","versions":[3]},{"name":"StorageProvisioner","versions":[3]},{"name":"StringsWatcher","versions":[1]},{"name":"Subnets","versions":[2]},{"name":"Undertaker","versions":[1]},{"name":"UnitAssigner","versions":[1]},{"name":"Uniter","versions":[4]},{"name":"Upgrader","versions":[1]},{"name":"VolumeAttachmentsWatcher","versions":[2]}],"server-version":"2.0.0"}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {},\n  "request": "WatchAll",\n  "version": 1,\n  "request-id": 3,\n  "type": "Client"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":3,"response":{"watcher-id":"1"}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "AllWatcher",\n  "params": {},\n  "request-id": 4,\n  "request": "Next",\n  "Id": "1",\n  "version": 1\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"response":{"deltas":[]}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "AllWatcher",\n  "params": {},\n  "request-id": 5,\n  "request": "Next",\n  "Id": "1",\n  "version": 1\n}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {},\n  "request": "ModelInfo",\n  "version": 1,\n  "request-id": 3,\n  "type": "Client"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":3,"response":{"name":"test","uuid":"9a87a64b-864c-4c53-8116-0582cdf223a4","controller-uuid":"","provider-type":"ec2","default-series":"xenial","cloud-tag":"cloud-aws","cloud-region":"eu-west-1","cloud-credential-tag":"cloudcred-aws_admin_aws-qrama","owner-tag":"user-admin","life":"alive","status":{"status":"","info":"","since":null},"users":null,"machines":null}}')
DEBUG:juju.model:Got ModelInfo: {'life': 'alive', 'controller_uuid': '', 'machines': [], 'cloud_tag': 'cloud-aws', 'provider_type': 'ec2', 'cloud_region': 'eu-west-1', 'uuid': '9a87a64b-864c-4c53-8116-0582cdf223a4', 'cloud_credential_tag': 'cloudcred-aws_admin_aws-qrama', 'status': <juju.client._client.EntityStatus object at 0x7f077c546b00>, 'default_series': 'xenial', 'owner_tag': 'user-admin', 'name': 'test', 'users': []}
9a87a64b-864c-4c53-8116-0582cdf223a4
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.jujucharms.com:443 "GET /charmstore/v5/ubuntu-10/meta/any HTTP/1.1" 200 21
DEBUG:juju.model:Deploying cs:ubuntu-10
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {\n    "channel": "stable",\n    "url": "cs:ubuntu-10"\n  },\n  "request": "AddCharm",\n  "version": 1,\n  "request-id": 4,\n  "type": "Client"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "params": {\n    "applications": [\n      {\n        "series": "trusty",\n        "resources": null,\n        "storage": null,\n        "config": null,\n        "num-units": 1,\n        "charm-url": "cs:ubuntu-10",\n        "application": "ubuntu",\n        "endpoint-bindings": null,\n        "channel": "stable",\n        "placement": [],\n        "config-yaml": null,\n        "constraints": null\n      }\n    ]\n  },\n  "request": "Deploy",\n  "version": 3,\n  "request-id": 5,\n  "type": "Application"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":5,"error":"unknown version (3) of interface \\"Application\\"","error-code":"not implemented","response":{}}')
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<run() done, defined at test.py:8> exception=JujuAPIError('unknown version (3) of interface "Application"',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 34, in run
    channel='stable',
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1045, in deploy
    result = await app_facade.Deploy([app])
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 317, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/_client.py", line 7618, in Deploy
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 436, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 95, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: unknown version (3) of interface "Application"
```

**Comment by tvansteenburgh** [comment]
The problem is your controller is running v2.0.0, and the first release of libjuju was built against v2.0.1. In that release, the Application facade version was incremented (to version 3). In other words, the client (libjuju) needs v3 of that facade, but the server is only advertising v1 and v2.

Basically you need to upgrade your controller. 

There is an issue for improving our version handling here: https://github.com/juju/python-libjuju/issues/49

**Comment by mhmoerma** [comment]
Thanks, this fixed it!
