### ISSUE TITLE
model.get_status() returns a None value

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#86]
```
controller_endpoint = 'x.x.x.x:17070'
user = '<user>'
password = '<pass>'
model_uuid = '<uuid>'


def execute_task(command):
    loop = asyncio.get_event_loop()
    loop.set_debug(False)
    loop.run_until_complete(command())

async def run(): 
    model = Model()
    await model.connect(controller_endpoint, model_uuid, user, password)
    print(model.get_status())

execute_task(run)
```
When I try to get my model status I see that a None is printed. My endpoint, user, password and model_uuid are right because when I replace `model.get_status()` by `model.state.__dict__` I get the json with my model information

**Comment by tvansteenburgh** [comment]
You need to await it:

```
print(await model.get_status())
```

**Comment by sebastienpattyn93** [comment]
I did that earlier but it returned the following error:

```
Traceback (most recent call last):
  File "libjujutest.py", line 44, in <module>
    execute_task(run)
  File "libjujutest.py", line 34, in execute_task
    loop.run_until_complete(command())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "libjujutest.py", line 40, in run
    print(await model.get_status())
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by tvansteenburgh** [comment]
Are you running from master? Model.get_status() wasn't implemented in 0.3.0 - it's in master but not released yet.

**Comment by sebastienpattyn93** [comment]
Ok, but then I should be able to catch it with a NotImplementedError?

**Comment by tvansteenburgh** [comment]
Hrm. Does `examples/fullstatus.py` work for you?

I would set a pdb breakpoint right before your call to model.get_status(), step into it and call the FullStatus() api and see what you get back.

**Comment by sebastienpattyn93** [comment]
the example returns an error on the `Connection.connect_current()`

```
Traceback (most recent call last):
  File "libjujutest.py", line 56, in <module>
    conn = loop.run_until_complete(Connection.connect_current())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 174, in connect_current
    '{}:{}'.format(controller_name, model_name))
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 225, in connect_model
    endpoint, model_uuid, username, password, cacert, macaroons)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 138, in connect
    await client.login(username, password, macaroons)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 248, in login
    "macaroons": macaroons or []
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 93, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: no credentials provided
```
using pdb I got this

```
> /home/sebastien/Documents/python-tests/libjujutest.py(17)<module>()
-> import asyncio
(Pdb) c
> /home/sebastien/Documents/python-tests/libjujutest.py(41)run()
-> await model.get_status()
(Pdb) s
--Call--
> /usr/local/lib/python3.5/dist-packages/juju/model.py(1194)get_status()
-> def get_status(self, filter_=None, utc=False):
(Pdb) s
> /usr/local/lib/python3.5/dist-packages/juju/model.py(1201)get_status()
-> pass
(Pdb) s
--Return--
> /usr/local/lib/python3.5/dist-packages/juju/model.py(1201)get_status()->None
-> pass
(Pdb) s
TypeError: object NoneType can't be used in 'await' expression
> /home/sebastien/Documents/python-tests/libjujutest.py(41)run()
-> await model.get_status()
(Pdb) s
> /home/sebastien/Documents/python-tests/libjujutest.py(42)run()
-> except NotImplementedError as e:
(Pdb) s
--Return--
> /home/sebastien/Documents/python-tests/libjujutest.py(42)run()->None
-> except NotImplementedError as e:
(Pdb) s
TypeError: object NoneType can't be used in 'await' expression
```
Not sure when to use the FullStatus() api when I'm debugging

**Comment by tvansteenburgh** [comment]
This is the problem:

```
> /usr/local/lib/python3.5/dist-packages/juju/model.py(1201)get_status()
-> pass
```

This indicates that you don't have the latest code from master.

**Comment by sebastienpattyn93** [comment]
thank you, my exception is now caught. I'll keep an eye on the following release notes.
