### ISSUE TITLE
[Bug]: juju.errors.JujuError: ('Unknown series : %s', 'kubernetes')

### ISSUE THREAD

**Issue by beliaev-maksim** [juju/python-libjuju#865]
### Description

regression for podspecs in 2.9.42.3

https://github.com/canonical/kubeflow-tensorboards-operator/actions/runs/5122909021/jobs/9212661327?pr=70

```
Traceback (most recent call last):
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/tests/integration/test_charms.py", line 22, in test_build_and_deploy_with_relations
    await ops_test.model.deploy(
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1690, in deploy
    base = utils.get_local_charm_base(charm_series, charm_dir, client.Base)
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/juju/utils.py", line 347, in get_local_charm_base
    channel_for_base = get_series_version(series) if series else ''
  File "/home/runner/work/kubeflow-tensorboards-operator/kubeflow-tensorboards-operator/.tox/integration/lib/python3.8/site-packages/juju/utils.py", line 322, in get_series_version
    raise errors.JujuError("Unknown series : %s", series_name)
juju.errors.JujuError: ('Unknown series : %s', 'kubernetes')
```

### Urgency

Blocker for our release

### Python-libjuju version

2.9.42.3

### Juju version

2.9.42

### Reproduce / Test

```python
https://github.com/canonical/kubeflow-tensorboards-operator/actions/runs/5122909021/jobs/9212661327?pr=70
```

**Comment by DnPlas** [comment]
Adding a bit extra information, this is also happening on pythonlib-juju 2.9.42.2 and 2.9.42.1, but the error is not seen in 3.0.4 (now EOL), which suggests this is a regression.
