### ISSUE TITLE
[Bug]: Error when trying to consume a cross-model relation

### ISSUE THREAD

**Issue by Gmerold** [juju/python-libjuju#878]
### Description

Hello Team,
While working on integration tests for Charmed SD-Core, I've noticed a problem with consuming a cross-model relation. Please find all the details below.

**Integration test scenario:**
1. Deploy [SD-Core bundle](https://charmhub.io/sdcore)
2. Create new model and deploy [COS Lite](https://github.com/canonical/cos-lite-bundle)
3. Offer `prometheus:receive-remote-write` from the COS model:
```python
await ops_test.model.create_offer(
    endpoint="prometheus:receive-remote-write",
    offer_name="prometheus",
    application_name="prometheus",
)
```
5. Consume `prometheus:receive-remote-write` in the SD-Core model:
```python
await ops_test.model.consume(
    endpoint="admin/cos-lite.prometheus",
    application_alias="prometheus",
)
```

**Error:**
```shell
Traceback (most recent call last):
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 557, in portforward_call
    websocket = create_websocket(configuration, url, headers)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 487, in create_websocket
    websocket.connect(url, **connect_opt)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/websocket/_http.py", line 136, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/websocket/_http.py", line 271, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/websocket/_http.py", line 219, in _wrap_sni_socket
    context.load_verify_locations(cafile=cafile, capath=capath)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/tests/integration/test_integration.py", line 21, in setup
    await self._deploy_sdcore_bundle(ops_test)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/tests/integration/test_integration.py", line 43, in _deploy_sdcore_bundle
    await ops_test.model.consume(
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/model.py", line 2440, in consume
    await source._connect_direct(**kwargs)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/controller.py", line 161, in _connect_direct
    await self._connector.connect(**kwargs)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/client/connector.py", line 75, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/client/connection.py", line 338, in connect
    self.proxy.connect()
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/juju/client/proxy/kubernetes/proxy.py", line 51, in connect
    self.port_forwarder = portforward(
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/stream/stream.py", line 35, in _websocket_request
    return api_method(*args, **kwargs)
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 1142, in connect_get_namespaced_pod_portforward
    return self.connect_get_namespaced_pod_portforward_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 1229, in connect_get_namespaced_pod_portforward_with_http_info
    return self.api_client.call_api(
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/home/gmerold/REPOS/Charmed_5G_Core/sdcore-tests/.tox/integration/lib/python3.10/site-packages/kubernetes/stream/ws_client.py", line 560, in portforward_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.exceptions.ApiException: (0)
Reason: [Errno 2] No such file or directory
```

**Working workaround:**
```python
run_args_consume = [
    "juju",
    "consume",
    "cos-lite.prometheus",
]
retcode, stdout, stderr = await ops_test.run(*run_args_consume)
if retcode != 0:
    raise RuntimeError(f"Error: {stderr}")
```

Cheers,
Bartek

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.1.2.0, 3.2.0.0

### Juju version

3.1.2-genericlinux-amd64

### Reproduce / Test

```python
Snippets available in the description.
```

**Comment by juanmanuel-tirado** [comment]
This could be related to #877
