### ISSUE TITLE
[Bug]: Juju scp on k8s unit doesn't work

### ISSUE THREAD

**Issue by yanksyoon** [juju/python-libjuju#885]
### Description

Using `unit.scp_to` throws an error because the `self.machine` of a Unit is a `NoneType`. 

I believe that any k8s charm that uses the `self.machine` within the Unit class (def scp_to, def scp_from, def ssh) all exhibit the same behavior. 

```
Traceback (most recent call last):
  File "/tests/integration/test_jenkins.py", line 82, in test_jenkins_automatic_update_out_of_range
    await unit.scp_to(
  File "/integration/lib/python3.10/site-packages/juju/unit.py", line 294, in scp_to
    await self.machine.scp_to(source, destination, user=user, proxy=proxy,
AttributeError: 'NoneType' object has no attribute 'scp_to'
```

### Urgency

Casually reporting

### Python-libjuju version

3.0.4

### Juju version

2.9.43

### Reproduce / Test

```python
from tempfile import NamedTemporaryFile

from juju.application import Application
from juju.model import Model
from juju.unit import Unit
from pytest_operator.plugin import OpsTest


async def test_reproduce(ops_test: OpsTest):
    model: Model = ops_test.model
    application: Application = await model.deploy("wordpress-k8s")
    await model.wait_for_idle()
    unit: Unit = application.units[0]

    with NamedTemporaryFile() as temp_file:
        temp_file.write("testing".encode())
        await unit.scp_to(temp_file.name, "/var/lib/")
```
```

**Comment by cderici** [comment]
Can you try this with https://github.com/juju/python-libjuju/releases/tag/2.9.43.0 and see if this is still happening? Thanks!
