### ISSUE TITLE
Problem with ModelModifyAccess

### ISSUE THREAD

**Issue by mhmoerma** [juju/python-libjuju#93]
I'm writing the grant-wrapper in model.py, however, using the following code,
```
async def grant(self, username, acl='read'):  #line number 1117
        """Grant a user access to this model.

        :param str username: Username
        :param str acl: Access control ('read' or 'write')

        """
        model_facade = client.ModelManagerFacade()
        model_facade.connect(self.connection)
        user = tag.user(username)
        model = tag.model(self.info.name)
        action = 'revoke'
        changes = client.ModifyModelAccess(acl, action, user, model)
        await model_facade.ModifyModelAccess([changes])
        action = 'grant'
        changes = client.ModifyModelAccess(acl, action, user, model)
        return await model_facade.ModifyModelAccess([changes])
```
I get the following error:
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:websocket:Driver connected to juju wss://xxx.xxx.xxx.xxx/model/0c6d354d-fbb0-41cc-856e-6942be7968a8/api
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 3,\n  "type": "Admin",\n  "request-id": 1,\n  "params": {},\n  "request": "RedirectInfo"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":1,"error":"not redirected","response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 3,\n  "type": "Admin",\n  "request-id": 2,\n  "params": {\n    "credentials": "xxx",\n    "nonce": "DmMy(n\\r35*0&",\n    "macaroons": [],\n    "auth-tag": "user-admin"\n  },\n  "request": "Login"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":2,"response":{"servers":[[{"value":"xxx.xxx.xxx.xxx","type":"ipv4","scope":"public","port":17070},{"value":"10.140.0.8","type":"ipv4","scope":"local-cloud","port":17070},{"value":"127.0.0.1","type":"ipv4","scope":"local-machine","port":17070},{"value":"::1","type":"ipv6","scope":"local-machine","port":17070}]],"model-tag":"model-0c6d354d-fbb0-41cc-856e-6942be7968a8","controller-tag":"controller-02e4ed54-b887-4a34-8ad5-4d5196837ec8","user-info":{"display-name":"","identity":"user-admin","last-connection":"2017-03-20T13:54:26Z","controller-access":"superuser","model-access":"admin"},"facades":[{"name":"Action","versions":[2]},{"name":"Agent","versions":[2]},{"name":"AgentTools","versions":[1]},{"name":"AllWatcher","versions":[1]},{"name":"Annotations","versions":[2]},{"name":"Application","versions":[1,2,3]},{"name":"ApplicationRelationsWatcher","versions":[1]},{"name":"ApplicationScaler","versions":[1]},{"name":"Backups","versions":[1]},{"name":"Block","versions":[2]},{"name":"Bundle","versions":[1]},{"name":"CharmRevisionUpdater","versions":[2]},{"name":"Charms","versions":[2]},{"name":"Cleaner","versions":[2]},{"name":"Client","versions":[1]},{"name":"Deployer","versions":[1]},{"name":"DiscoverSpaces","versions":[2]},{"name":"DiskManager","versions":[2]},{"name":"EntityWatcher","versions":[2]},{"name":"FilesystemAttachmentsWatcher","versions":[2]},{"name":"Firewaller","versions":[3]},{"name":"HighAvailability","versions":[2]},{"name":"HostKeyReporter","versions":[1]},{"name":"ImageManager","versions":[2]},{"name":"ImageMetadata","versions":[2]},{"name":"InstancePoller","versions":[3]},{"name":"KeyManager","versions":[1]},{"name":"KeyUpdater","versions":[1]},{"name":"LeadershipService","versions":[2]},{"name":"LifeFlag","versions":[1]},{"name":"LogForwarding","versions":[1]},{"name":"Logger","versions":[1]},{"name":"MachineActions","versions":[1]},{"name":"MachineManager","versions":[2]},{"name":"MachineUndertaker","versions":[1]},{"name":"Machiner","versions":[1]},{"name":"MeterStatus","versions":[1]},{"name":"MetricsAdder","versions":[2]},{"name":"MetricsDebug","versions":[2]},{"name":"MetricsManager","versions":[1]},{"name":"MigrationFlag","versions":[1]},{"name":"MigrationMaster","versions":[1]},{"name":"MigrationMinion","versions":[1]},{"name":"MigrationStatusWatcher","versions":[1]},{"name":"ModelConfig","versions":[1]},{"name":"NotifyWatcher","versions":[1]},{"name":"Payloads","versions":[1]},{"name":"PayloadsHookContext","versions":[1]},{"name":"Pinger","versions":[1]},{"name":"Provisioner","versions":[3]},{"name":"ProxyUpdater","versions":[1]},{"name":"Reboot","versions":[2]},{"name":"RelationUnitsWatcher","versions":[1]},{"name":"Resources","versions":[1]},{"name":"ResourcesHookContext","versions":[1]},{"name":"Resumer","versions":[2]},{"name":"RetryStrategy","versions":[1]},{"name":"SSHClient","versions":[1,2]},{"name":"Singular","versions":[1]},{"name":"Spaces","versions":[2]},{"name":"StatusHistory","versions":[2]},{"name":"Storage","versions":[3]},{"name":"StorageProvisioner","versions":[3]},{"name":"StringsWatcher","versions":[1]},{"name":"Subnets","versions":[2]},{"name":"Undertaker","versions":[1]},{"name":"UnitAssigner","versions":[1]},{"name":"Uniter","versions":[4]},{"name":"Upgrader","versions":[1]},{"name":"VolumeAttachmentsWatcher","versions":[2]}],"server-version":"2.0.3"}}')
DEBUG:juju.model:Starting watcher task
INFO:websocket:Driver connected to juju wss://xxx.xxx.xxx.xxx:17070/model/0c6d354d-fbb0-41cc-856e-6942be7968a8/api
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 3,\n  "type": "Admin",\n  "request-id": 1,\n  "params": {},\n  "request": "RedirectInfo"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":1,"error":"not redirected","response":{}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 3,\n  "type": "Admin",\n  "request-id": 2,\n  "params": {\n    "credentials": "xxx",\n    "nonce": "hm5$<ZD\\u000b \'E\\"",\n    "macaroons": [],\n    "auth-tag": "user-admin"\n  },\n  "request": "Login"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":2,"response":{"servers":[[{"value":"35.185.152.227","type":"ipv4","scope":"public","port":17070},{"value":"10.140.0.8","type":"ipv4","scope":"local-cloud","port":17070},{"value":"127.0.0.1","type":"ipv4","scope":"local-machine","port":17070},{"value":"::1","type":"ipv6","scope":"local-machine","port":17070}]],"model-tag":"model-0c6d354d-fbb0-41cc-856e-6942be7968a8","controller-tag":"controller-02e4ed54-b887-4a34-8ad5-4d5196837ec8","user-info":{"display-name":"","identity":"user-admin","last-connection":"2017-03-20T13:54:42Z","controller-access":"superuser","model-access":"admin"},"facades":[{"name":"Action","versions":[2]},{"name":"Agent","versions":[2]},{"name":"AgentTools","versions":[1]},{"name":"AllWatcher","versions":[1]},{"name":"Annotations","versions":[2]},{"name":"Application","versions":[1,2,3]},{"name":"ApplicationRelationsWatcher","versions":[1]},{"name":"ApplicationScaler","versions":[1]},{"name":"Backups","versions":[1]},{"name":"Block","versions":[2]},{"name":"Bundle","versions":[1]},{"name":"CharmRevisionUpdater","versions":[2]},{"name":"Charms","versions":[2]},{"name":"Cleaner","versions":[2]},{"name":"Client","versions":[1]},{"name":"Deployer","versions":[1]},{"name":"DiscoverSpaces","versions":[2]},{"name":"DiskManager","versions":[2]},{"name":"EntityWatcher","versions":[2]},{"name":"FilesystemAttachmentsWatcher","versions":[2]},{"name":"Firewaller","versions":[3]},{"name":"HighAvailability","versions":[2]},{"name":"HostKeyReporter","versions":[1]},{"name":"ImageManager","versions":[2]},{"name":"ImageMetadata","versions":[2]},{"name":"InstancePoller","versions":[3]},{"name":"KeyManager","versions":[1]},{"name":"KeyUpdater","versions":[1]},{"name":"LeadershipService","versions":[2]},{"name":"LifeFlag","versions":[1]},{"name":"LogForwarding","versions":[1]},{"name":"Logger","versions":[1]},{"name":"MachineActions","versions":[1]},{"name":"MachineManager","versions":[2]},{"name":"MachineUndertaker","versions":[1]},{"name":"Machiner","versions":[1]},{"name":"MeterStatus","versions":[1]},{"name":"MetricsAdder","versions":[2]},{"name":"MetricsDebug","versions":[2]},{"name":"MetricsManager","versions":[1]},{"name":"MigrationFlag","versions":[1]},{"name":"MigrationMaster","versions":[1]},{"name":"MigrationMinion","versions":[1]},{"name":"MigrationStatusWatcher","versions":[1]},{"name":"ModelConfig","versions":[1]},{"name":"NotifyWatcher","versions":[1]},{"name":"Payloads","versions":[1]},{"name":"PayloadsHookContext","versions":[1]},{"name":"Pinger","versions":[1]},{"name":"Provisioner","versions":[3]},{"name":"ProxyUpdater","versions":[1]},{"name":"Reboot","versions":[2]},{"name":"RelationUnitsWatcher","versions":[1]},{"name":"Resources","versions":[1]},{"name":"ResourcesHookContext","versions":[1]},{"name":"Resumer","versions":[2]},{"name":"RetryStrategy","versions":[1]},{"name":"SSHClient","versions":[1,2]},{"name":"Singular","versions":[1]},{"name":"Spaces","versions":[2]},{"name":"StatusHistory","versions":[2]},{"name":"Storage","versions":[3]},{"name":"StorageProvisioner","versions":[3]},{"name":"StringsWatcher","versions":[1]},{"name":"Subnets","versions":[2]},{"name":"Undertaker","versions":[1]},{"name":"UnitAssigner","versions":[1]},{"name":"Uniter","versions":[4]},{"name":"Upgrader","versions":[1]},{"name":"VolumeAttachmentsWatcher","versions":[2]}],"server-version":"2.0.3"}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 1,\n  "type": "Client",\n  "request-id": 3,\n  "params": {},\n  "request": "WatchAll"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":3,"response":{"watcher-id":"1"}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "AllWatcher",\n  "params": {},\n  "request": "Next",\n  "Id": "1",\n  "version": 1,\n  "request-id": 4\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"response":{"deltas":[]}}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "type": "AllWatcher",\n  "params": {},\n  "request": "Next",\n  "Id": "1",\n  "version": 1,\n  "request-id": 5\n}')
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 1,\n  "type": "Client",\n  "request-id": 3,\n  "params": {},\n  "request": "ModelInfo"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":3,"response":{"name":"default","uuid":"0c6d354d-fbb0-41cc-856e-6942be7968a8","controller-uuid":"","provider-type":"gce","default-series":"xenial","cloud-tag":"cloud-google","cloud-region":"asia-east1","cloud-credential-tag":"cloudcred-google_admin_qrama","owner-tag":"user-admin","life":"alive","status":{"status":"","info":"","since":null},"users":null,"machines":null}}')
DEBUG:juju.model:Got ModelInfo: {'life': 'alive', 'provider_type': 'gce', 'owner_tag': 'user-admin', 'name': 'default', 'users': [], 'machines': [], 'cloud_credential_tag': 'cloudcred-google_admin_qrama', 'default_series': 'xenial', 'cloud_tag': 'cloud-google', 'status': <juju.client._client.EntityStatus object at 0x7f55a0786b70>, 'cloud_region': 'asia-east1', 'controller_uuid': '', 'uuid': '0c6d354d-fbb0-41cc-856e-6942be7968a8'}
DEBUG:websockets.protocol:client >> Frame(fin=True, opcode=1, data=b'{\n  "version": 2,\n  "type": "ModelManager",\n  "request-id": 4,\n  "params": {\n    "changes": [\n      {\n        "model-tag": "user-test",\n        "action": "revoke",\n        "access": "write",\n        "user-tag": "model-default"\n      }\n    ]\n  },\n  "request": "ModifyModelAccess"\n}')
DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"request-id":4,"error":"facade \\"ModelManager\\" not supported for model API connection","error-code":"not supported","response":{}}')
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<run() done, defined at test.py:9> exception=JujuAPIError('facade "ModelManager" not supported for model API connection',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 25, in run
    res = await model.grant('test', 'write')
  File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 1130, in grant
    await model_facade.ModifyModelAccess([changes])
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 317, in wrapper
    reply = await f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/_client.py", line 15279, in ModifyModelAccess
    reply = await self.rpc(msg)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/facade.py", line 436, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/usr/local/lib/python3.5/dist-packages/juju/client/connection.py", line 95, in rpc
    raise JujuAPIError(result)
juju.errors.JujuAPIError: facade "ModelManager" not supported for model API connection
```
Testscript
```
import asyncio
import logging

from juju.controller import Controller
from juju.model import Model

logging.basicConfig(level=logging.DEBUG)

async def run():
    model = Model()

    controller_endpoint = 'xxx.xxx.xxx.xxx:17070'
    username = 'admin'
    password = 'xxx'
    muuid = '0c6d354d-fbb0-41cc-856e-6942be7968a8'

    cacert = None

    await model.connect(
        controller_endpoint,
        muuid,
        username,
        password,
    )
    res = await model.grant('test', 'write')
    print(res.serialize()['results'][0].serialize())
    await controller.disconnect()


logging.basicConfig(level=logging.DEBUG)
ws_logger = logging.getLogger('websockets.protocol')
ws_logger.setLevel(logging.DEBUG)
loop = asyncio.get_event_loop()
loop.set_debug(False)
loop.create_task(run())
loop.run_forever()
```

**Comment by tvansteenburgh** [comment]
The error indicates that ModelManager facade can only be called on a Controller api connection, not a Model api connection. You can get a controller connection from a model connection with `controller_conn = model.connection.controller()`.

**Comment by mhmoerma** [comment]
Thanks. This fixed it. Do you have some extra info about the model-tags as well? Using `model = tag.model(self.info.name)` results in a `{'code': '', 'info': None, 'message': 'could not modify model access: "model-default" is not a valid model tag'}` error

**Comment by tvansteenburgh** [comment]
I think you need to pass it the model uuid, not the name.

**Comment by mhmoerma** [comment]
Indeed, now it works. Thanks!
