### ISSUE TITLE
ssl.SSLCertVerificationErro when model.connect() with cacert

### ISSUE THREAD

**Issue by erik78se** [juju/python-libjuju#994]
### Description

I'm trying to use juju to write an application. I have this example code, also taken from this repo examples.

I encountered an SSL error and decided to add the cacert from the controllers.yaml

But I still cant get it to work. I've opened up a discussion on the juju community discourse here: https://discourse.charmhub.io/t/pylibjuju-2-9-46-0-release-notes/12754/3?u=erik-lonroth

This is my setup:
```

* juju==2.9.46.0
* Controller: 2.9.46
* Python 3.10.12
```

This is the example code:

```
from juju import jasyncio
from juju.model import Model
import jconf

# Get cacert
cacert = jconf.get_controller_cacert('local-lxd')

cacert = """
-----BEGIN CERTIFICATE-----
MIIEEjCCAnqgAwIBAgIUE96s5r4qe8KjVyRXbbdu/BywlfUwDQYJKoZIhvcNAQEL
BQAwITENMAsGA1UEChMESnVqdTEQMA4GA1UEAxMHanVqdS1jYTAeFw0yMzA1MjUx
ODMyMzVaFw0zMzA1MjUxODM3MzVaMCExDTALBgNVBAoTBEp1anUxEDAOBgNVBAMT
B2p1anUtY2EwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDlX7UYF6uc
nEls1RsWjBHrg7KcI2ZX+dW0icLV+2eu9eE6/yuWsRBf6WwCK54WO1HRyiZ+BxaJ
mAE+L4Zc4230M5nylmwlP81xp+xrS1i1lzAxMybTTXySydAIZ7C8qyXMgdaP3f9Y
ZMf4qIdsZl1lKv5YQ0cXrUpnNWjNY4X5Uy1gYBK85Ap7Bm9hMd3viGT0svtX7n6q
uSs+7yFdVAqw12JmBP/tlRVdoE6UNX8nTc0BFO0pB2qYe8VarUnY96YHJgA0kwG7
8RbyQ4+1w7lF8wAHlMB4gFmNei4YjUrRtIiZ4qSB/JGmwsZSSzNaB+9+9Iw3MjJO
pSdEWxXG2Y3IHiZALXwzV1iaKItVfGxRch3hVYLOOCc2LkK3dyk/vfxumG3Thm2h
OFbky5KS3Kk+lg31GB2tdlhWxlIfyNqmJZczoZeBSzNEv6dGImSPo2ySXZPp+dW1
g2nJ3fslyKrBUm4aaALflldnV++OwKjl7bBPrEJKxygDpD19DZ5OpZUCAwEAAaNC
MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLcl
ke6r2p2EzRNE1tLizKAJC7NwMA0GCSqGSIb3DQEBCwUAA4IBgQCpc+1Dqc5jwkoi
G+e426H/EoK9YDDxblqRSMxV0Jxib9pV2hvhe511gMK+dJzVNK5VQw7lu5Xu3YSw
Ko0OVa0mxQMdj5UKBcTO8tUHqloGYd6cYOGU8EVi8/4NBvfoZlegDl9YV7LY7yV8
5pM5AQ+9dmAAIfzpObDzxHHEyzO5mOnCZlEoInaS8K9hRqw1lI38mUib4xcLq9Nh
oe7IyzgXlNE1l8896DZCWoQHC6lfBaWt1zlGsjYW6b+VaPG78UyT/6hLHZ8NDy2r
K2EwCXfm1JEWAyEjWzPWrveLrVryOiWHAiPcOWfWJEeMXIH1EVRZSKl2/sJ7GeUY
CM3KIhkNF2n38WXNGt9asEeA9Z979ha3lMIFo0GGb77uaRxC6VD3qI4tYonnDnOd
qDdA5cTrvz4jEQPAF495YjCLJSzD2iRxfE/F0EPltljMfv4KJflNwXwCMGs70RYQ
6fGj+cwU+IcgwVo7Js0Ks/lVBLad9iqRZNRIpi6tJylP0a8R1wE=
-----END CERTIFICATE-----
"""

async def status():
    model = Model()
    await model.connect(model_name='local-lxd:admin/tutorial', username='erik-local', password='123456789', cacert=cacert)

    status = await model.get_status()
    await model.disconnect()

    print('Applications:', list(status.applications.keys()))
    print('Machines:', list(status.machines.keys()))
    print('Relations:', status.relations)

    return status

if __name__ == '__main__':
    jasyncio.run(status())

```

This is the error:

```
python3 smalltest.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.51.45.220', port=17070): Max retries exceeded with url: /auth/discharge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/smalltest.py", line 49, in <module>
    jasyncio.run(status())
  File "/usr/local/lib/python3.10/dist-packages/juju/jasyncio.py", line 120, in run
    raise task.exception()
  File "/root/smalltest.py", line 37, in status
    await model.connect(model_name='local-lxd:admin/tutorial', username='erik-local', password='123456789', cacert=cacert)
  File "/usr/local/lib/python3.10/dist-packages/juju/model.py", line 703, in connect
    await self._connector.connect_model(model_name, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connector.py", line 184, in connect_model
    await self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connector.py", line 83, in connect
    self._connection = await Connection.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 354, in connect
    raise lastError
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 343, in connect
    await self._connect_with_redirect([_ep])
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 862, in _connect_with_redirect
    login_result = await self._connect_with_login(endpoints)
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 841, in _connect_with_login
    self.bakery_client.handle_error(
  File "/usr/local/lib/python3.10/dist-packages/macaroonbakery/httpbakery/_client.py", line 101, in handle_error
    discharges = bakery.discharge_all(
  File "/usr/local/lib/python3.10/dist-packages/macaroonbakery/bakery/_discharge.py", line 77, in discharge_all
    dm = get_discharge(cav.cav, cav.encrypted_caveat)
  File "/usr/local/lib/python3.10/dist-packages/macaroonbakery/httpbakery/_client.py", line 130, in acquire_discharge
    resp = self._acquire_discharge_with_token(cav, payload, None)
  File "/usr/local/lib/python3.10/dist-packages/macaroonbakery/httpbakery/_client.py", line 180, in _acquire_discharge_with_token
    return self.request('POST', target, data=req, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/macaroonbakery/httpbakery/_client.py", line 87, in request
    return requests.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.51.45.220', port=17070): Max retries exceeded with url: /auth/discharge (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.46.0

### Juju version

2.9.46

### Reproduce / Test

```python
from juju import jasyncio
from juju.model import Model
import jconf

# Get cacert
cacert = jconf.get_controller_cacert('local-lxd')

cacert = """
-----BEGIN CERTIFICATE-----
MIIEEjCCAnqgAwIBAgIUE96s5r4qe8KjVyRXbbdu/BywlfUwDQYJKoZIhvcNAQEL
BQAwITENMAsGA1UEChMESnVqdTEQMA4GA1UEAxMHanVqdS1jYTAeFw0yMzA1MjUx
ODMyMzVaFw0zMzA1MjUxODM3MzVaMCExDTALBgNVBAoTBEp1anUxEDAOBgNVBAMT
B2p1anUtY2EwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDlX7UYF6uc
nEls1RsWjBHrg7KcI2ZX+dW0icLV+2eu9eE6/yuWsRBf6WwCK54WO1HRyiZ+BxaJ
mAE+L4Zc4230M5nylmwlP81xp+xrS1i1lzAxMybTTXySydAIZ7C8qyXMgdaP3f9Y
ZMf4qIdsZl1lKv5YQ0cXrUpnNWjNY4X5Uy1gYBK85Ap7Bm9hMd3viGT0svtX7n6q
uSs+7yFdVAqw12JmBP/tlRVdoE6UNX8nTc0BFO0pB2qYe8VarUnY96YHJgA0kwG7
8RbyQ4+1w7lF8wAHlMB4gFmNei4YjUrRtIiZ4qSB/JGmwsZSSzNaB+9+9Iw3MjJO
pSdEWxXG2Y3IHiZALXwzV1iaKItVfGxRch3hVYLOOCc2LkK3dyk/vfxumG3Thm2h
OFbky5KS3Kk+lg31GB2tdlhWxlIfyNqmJZczoZeBSzNEv6dGImSPo2ySXZPp+dW1
g2nJ3fslyKrBUm4aaALflldnV++OwKjl7bBPrEJKxygDpD19DZ5OpZUCAwEAAaNC
MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLcl
ke6r2p2EzRNE1tLizKAJC7NwMA0GCSqGSIb3DQEBCwUAA4IBgQCpc+1Dqc5jwkoi
G+e426H/EoK9YDDxblqRSMxV0Jxib9pV2hvhe511gMK+dJzVNK5VQw7lu5Xu3YSw
Ko0OVa0mxQMdj5UKBcTO8tUHqloGYd6cYOGU8EVi8/4NBvfoZlegDl9YV7LY7yV8
5pM5AQ+9dmAAIfzpObDzxHHEyzO5mOnCZlEoInaS8K9hRqw1lI38mUib4xcLq9Nh
oe7IyzgXlNE1l8896DZCWoQHC6lfBaWt1zlGsjYW6b+VaPG78UyT/6hLHZ8NDy2r
K2EwCXfm1JEWAyEjWzPWrveLrVryOiWHAiPcOWfWJEeMXIH1EVRZSKl2/sJ7GeUY
CM3KIhkNF2n38WXNGt9asEeA9Z979ha3lMIFo0GGb77uaRxC6VD3qI4tYonnDnOd
qDdA5cTrvz4jEQPAF495YjCLJSzD2iRxfE/F0EPltljMfv4KJflNwXwCMGs70RYQ
6fGj+cwU+IcgwVo7Js0Ks/lVBLad9iqRZNRIpi6tJylP0a8R1wE=
-----END CERTIFICATE-----
"""

async def status():
    model = Model()
    await model.connect(model_name='local-lxd:admin/tutorial', username='erik-local', password='123456789', cacert=cacert)

    status = await model.get_status()
    await model.disconnect()

    print('Applications:', list(status.applications.keys()))
    print('Machines:', list(status.machines.keys()))
    print('Relations:', status.relations)

    return status

if __name__ == '__main__':
    jasyncio.run(status())
```

**Comment by erik78se** [comment]
I think I've found out that I need to supply the "endpoint" argument to the connect also for the cacert to work. I think this is not a bug for the SSL itself, but rather perhaps making the connect function be more expressive how it needs to be called properly.
