### ISSUE TITLE
credentials.yaml must be present or lib wont work

### ISSUE THREAD

**Issue by erik78se** [juju/python-libjuju#996]
### Description

I'm trying to use the juju library and have connection information in a database (endpoint,username,password,cacert)

But, when trying to connect to an endpoint, the credentials.yaml have to be available on the machine.

If its not, I get this error

`Error connecting to controller my-controller. Error: [Errno 2] No such file or directory: '/root/.local/share/juju/controllers.yaml'`

If I have the file present, the connection works.

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.46.0

### Juju version

2.9.46

### Reproduce / Test

```python
async def test_jcontroller_async(jcontroller_instance):
        """
        Tests connection to a Juju controller.
        Returns True if connection is successful, False otherwise.
        """
        logger = logging.getLogger(__name__)
        controller = Controller()
        try:
            logger.info("Connecting to controller: %s", jcontroller_instance.name)
            #TODO: Remove password from logging
            logger.debug("Credentials: %s, %s, %s", jcontroller_instance.username, 
                         jcontroller_instance.password, jcontroller_instance.cacert)
            await controller.connect(endpoint=jcontroller_instance.endpointUrl,
                                    username=jcontroller_instance.username,
                                    password=jcontroller_instance.password,
                                    cacert=jcontroller_instance.cacert)
            if controller.is_connected():
                logger.info("Successfully connected to controller: %s", jcontroller_instance.name)
                await controller.disconnect()
                return True
            else:
                logger.warning("Could not connect to controller: %s", jcontroller_instance.name)
                return False
        except Exception as e:
            logger.error("Error connecting to controller %s. Error: %s", jcontroller_instance.name, str(e))
            return False
```

**Comment by cderici** [comment]
Hi @erik78se, I don't seem to be able to reproduce this (like I deleted my `credentials.yaml` and it seems to be connecting properly). Could you please try again and help me reproduce if it's still happening? Thanks!

**Comment by cderici** [comment]
The only time that may be problematic is that if one of those auth parameters are missing (e.g. None) and pylibjuju tries to get it from the `credentials.yaml`, but even in that case it should fail with `connect() missing auth params` or `no credentials provided`.

**Comment by erik78se** [comment]
@cderici - did you manage to figure out what the problem was? I don't think I'm missing any parameter.

**Comment by erik78se** [comment]
I can still reproduce the error.

```
 ./connect-controller.py 
DEBUG:asyncio:Using selector: EpollSelector
-----BEGIN CERTIFICATE-----
REMOVED REMOVED REMOVED
-----END CERTIFICATE-----

DEBUG:websockets.client:= connection is CONNECTING
DEBUG:websockets.client:> GET /api HTTP/1.1
DEBUG:websockets.client:> Host: zz.zz.zz.zz:17070
DEBUG:websockets.client:> Upgrade: websocket
DEBUG:websockets.client:> Connection: Upgrade
DEBUG:websockets.client:> Sec-WebSocket-Key: ayERO+zEJvxRC2TEkTdwDw==
DEBUG:websockets.client:> Sec-WebSocket-Version: 13
DEBUG:websockets.client:> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
DEBUG:websockets.client:> User-Agent: Python/3.10 websockets/12.0
DEBUG:websockets.client:< HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:< Upgrade: websocket
DEBUG:websockets.client:< Connection: Upgrade
DEBUG:websockets.client:< Sec-WebSocket-Accept: 6BU45hF1tOAmh5k2VzoMys1uGkE=
DEBUG:websockets.client:= connection is OPEN
DEBUG:juju.client.connection:Driver connected to juju wss://zz.zz.zz.zz:17070/api
DEBUG:juju.client.connection:connection 140493337472320 -> {
  "type": "Admin",
  "request": "Login",
  "version": 3,
  "params": {
    "auth-tag": "user-zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
    "credentials": "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  },
  "request-id": 1
}
DEBUG:websockets.client:> TEXT '{\n  "type": "Admin",\n  "request": "Login",\n ...,\n  "request-id": 1\n}' [171 bytes]
DEBUG:websockets.client:< TEXT '{"request-id":1,"response":{"servers":[[{"value...r-version":"2.9.46"}}\n' [1285 bytes]
DEBUG:juju.client.connection:connection 1404920 <- {'request-id': 1, 'response': {'servers': [[{'value': 'zz.zzz.zz.zz', 'type': 'ipv4', 'scope': 'public', 'port': 17070}, {'value': 'zz.zz.zz.zz', 'type': 'ipv4', 'scope': 'local-cloud', 'port': 17070}, {'value': '252.17.173.1', 'type': 'ipv4', 'scope': 'local-fan', 'port': 17070}, {'value': '127.0.0.1', 'type': 'ipv4', 'scope': 'local-machine', 'port': 17070}, {'value': '::1', 'type': 'ipv6', 'scope': 'local-machine', 'port': 17070}]], 'controller-tag': 'controller-a9d8sdfda0f-2c6b-435e-82f2-d3789sdf8f7f2d3', 'user-info': {'display-name': '', 'identity': 'user-deployments-service', 'controller-access': 'login', 'model-access': ''}, 'facades': [{'name': 'AllModelWatcher', 'versions': [2, 3, 4]}, {'name': 'ApplicationOffers', 'versions': [1, 2, 3, 4]}, {'name': 'Bundle', 'versions': [1, 2, 3, 4, 5, 6]}, {'name': 'Cloud', 'versions': [1, 2, 3, 4, 5, 6, 7]}, {'name': 'Controller', 'versions': [3, 4, 5, 6, 7, 8, 9, 10, 11]}, {'name': 'CrossController', 'versions': [1]}, {'name': 'HighAvailability', 'versions': [2]}, {'name': 'MigrationTarget', 'versions': [1, 2]}, {'name': 'ModelConfig', 'versions': [1, 2, 3]}, {'name': 'ModelManager', 'versions': [2, 3, 4, 5, 6, 7, 8, 9]}, {'name': 'ModelSummaryWatcher', 'versions': [1]}, {'name': 'ModelUpgrader', 'versions': [1]}, {'name': 'NotifyWatcher', 'versions': [1]}, {'name': 'Pinger', 'versions': [1]}, {'name': 'UserManager', 'versions': [1, 2, 3]}], 'server-version': '2.9.46'}}
DEBUG:juju.client.connection:connection 14472320 -> {
  "type": "Pinger",
  "request": "Ping",
  "version": 1,
  "params": {},
  "request-id": 2
}
DEBUG:websockets.client:> TEXT '{\n  "type": "Pinger",\n  "request": "Ping",\n ...,\n  "request-id": 2\n}' [94 bytes]
Traceback (most recent call last):
  File "/root/deployments_site/jsync/./connect-controller.py", line 29, in <module>
    jasyncio.run(main())
  File "/usr/local/lib/python3.10/dist-packages/juju/jasyncio.py", line 120, in run
    raise task.exception()
  File "/root/deployments_site/jsync/./connect-controller.py", line 19, in main
    await controller.connect(endpoint="zz.zz.zz.zz:17070",
  File "/usr/local/lib/python3.10/dist-packages/juju/controller.py", line 138, in connect
    await self._connector.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connector.py", line 88, in connect
    self.controller_name = self.jujudata.controller_name_by_endpoint(kwargs['endpoint'])
  File "/usr/local/lib/python3.10/dist-packages/juju/client/jujudata.py", line 136, in controller_name_by_endpoint
    for controller_name, controller in self.controllers().items():
  File "/usr/local/lib/python3.10/dist-packages/juju/client/jujudata.py", line 149, in controllers
    return self._load_yaml('controllers.yaml', 'controllers')
  File "/usr/local/lib/python3.10/dist-packages/juju/client/jujudata.py", line 166, in _load_yaml
    with io.open(filepath, 'rt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/juju/controllers.yaml'
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<WebSocketCommonProtocol.keepalive_ping() running at /usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py:1254> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-12' coro=<Connection._pinger() running at /usr/local/lib/python3.10/dist-packages/juju/client/connection.py:573> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<Connection._receiver() running at /usr/local/lib/python3.10/dist-packages/juju/client/connection.py:531> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fc72762b340>
transport: <_SelectorSocketTransport closing fd=6>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at /usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py:1301> wait_for=<Task pending name='Task-4' coro=<WebSocketCommonProtocol.transfer_data() running at /usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), _wait.<locals>._on_completion() at /usr/lib/python3.10/asyncio/tasks.py:475]>>
DEBUG:websockets.client:x closing TCP connection
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7fc727644890>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 1337, in close_connection
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 1355, in close_transport
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 1379, in wait_for_connection_lost
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/async_timeout.py", line 74, in timeout
RuntimeError: no running event loop
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-13' coro=<Connection._pinger.<locals>._do_ping() running at /usr/local/lib/python3.10/dist-packages/juju/client/connection.py:566> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=<Logger juju....ction (DEBUG)>)() at /usr/local/lib/python3.10/dist-packages/juju/jasyncio.py:53]>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-10' coro=<WebSocketCommonProtocol.recv() running at /usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py:552> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=<Logger juju....ction (DEBUG)>)() at /usr/local/lib/python3.10/dist-packages/juju/jasyncio.py:53]>
Exception ignored in: <coroutine object Connection._pinger.<locals>._do_ping at 0x7fc72775bb50>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 566, in _do_ping
  File "/usr/local/lib/python3.10/dist-packages/juju/client/facade.py", line 486, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/juju/client/_client1.py", line 14077, in Ping
  File "/usr/local/lib/python3.10/dist-packages/juju/client/facade.py", line 659, in rpc
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 627, in rpc
  File "/usr/local/lib/python3.10/dist-packages/juju/client/connection.py", line 443, in _recv
  File "/usr/local/lib/python3.10/dist-packages/juju/utils.py", line 105, in get
  File "/usr/lib/python3.10/asyncio/queues.py", line 161, in get
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-14' coro=<Event.wait() running at /usr/lib/python3.10/asyncio/locks.py:214> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<Event.wait() running at /usr/lib/python3.10/asyncio/locks.py:214> wait_for=<Future pending cb=[Task.task_wakeup()]>>
(venv) root@django1:~/deployments_site/jsync# 

```
